### ISSUE TITLE
Support vertical layouts

### ISSUE THREAD

**Issue by RomanHargrave** [kwin-scripts/kwin-tiling#109]
I have two secondary displays, both of which are in vertical (H > W) configurations. kwin-tiling only lets me use horizontal layouts, where the master window is to the left or right of other windows; however, this results in a rather dis-satisfactory layout for vertical displays, as the windows are uselessly narrow and excessively tall.

**Comment by setzer22** [comment]
I don't think there's  a release yet, but I recently implemented manual layout with which you can easily create a vertical container. It still has some bugs, but if you can manage to obtain the latest version from this repository and set the layout to I3Layout, you should be able to create a vertical container by focusing one window, pressing Meta+V, and after that, opening a new application. Then all apps will be opened in a vertical position just as you need.

**Comment by RomanHargrave** [comment]
I do have the latest version, but the configuration dialog no longer allows selection of the layout, not that that's a problem.

**Comment by faho** [comment]
>the configuration dialog no longer allows selection of the layout

In that textbox at the bottom of the common options tab, you can enter stuff like "5:BladeLayout,2:SpiralLayout" (adding a "-" before the desktop number disables tiling on that desktop by default).

I'm sorry for the inconvenience - the widget we used for this got removed, and there doesn't appear to be a real substitute, so we're forced to use stupid hacks.

------

As for a vertical layout: PRs welcome!

**Comment by RomanHargrave** [comment]
>  I'm sorry for the inconvenience - the widget we used for this got removed, and there doesn't appear to be a real substitute, so we're forced to use stupid hacks.

Based on other discussions I had figured as much. For the time being I'm not using auto-layout, even though I would prefer to, as (unlike i3) KWin does not support having a diffent workspace (KWin "desktop") per display, therefore I can't say - dictate stacking on a per display basis.

**Comment by laloch** [comment]
Hi @RomanHargrave, would you mind testing #150?
