### ISSUE TITLE
[feature request] When borders are turned off for the active window, add a thin colored border around it

### ISSUE THREAD

**Issue by CrazyCrab** [kwin-scripts/kwin-tiling#11]
When borders are turned off for the windows, it's very difficult to see which one is active. It would be nice to add a very thing colored border around the active window if its borders are turned off (that's how it works in xmonad).

**Comment by piotr-dobrogost** [comment]
I think some ideas/code might be taken from Aurorae window decorations – https://store.kde.org/browse/cat/114/. Martin Gräßlin's blog posts about Aurorae engine – https://blog.martin-graesslin.com/blog/tag/aurorae/

**Comment by faho** [comment]
I don't think this would ever work properly. The best you can do right now is to enable gaps and keep window borders.
