### ISSUE TITLE
Gaps/tiling breaks (e.g. with lxterminal)

### ISSUE THREAD

**Issue by hhhorb** [kwin-scripts/kwin-tiling#111]
Hey, I commented on this at Reddit a few months ago, I'm finally opening a bug. I love your script! :D 

lxterminal...

https://cdn.scrot.moe/images/2018/09/20/Screenshot_20180920_034240.png

**Comment by faho** [comment]
It seems lxterminal has a

>program specified resize increment: 12 by 24

which means some of the math must be off.

**Comment by hhhorb** [comment]
Again, sorry for the late reply. I saw the same behavior using xfce4-terminal and rxvt-unicode.
