### ISSUE TITLE
Script is not actively tiling windows

### ISSUE THREAD

**Issue by RomanHargrave** [kwin-scripts/kwin-tiling#113]
I decided to have a crack at making this script work for me, again.
At some point between a5b9290 and f7dbbbc the script has ceased to enforce tiling. It also will not tile certain windows that certainly should not be blacklisted (e.g. Claws).

If I enable tiling, some of the windows on my desktop will tile initially; however, if I move a window or resize it, it will not snap in to the most appropriate tile area - it just stays 'floating'. If I use the `Tile Now` shortcut, it will tile.

**Comment by RomanHargrave** [comment]
@faho I apologize, I had somehow had the wrong hash in my clipboard. I believe I had meant to paste b7bb220

I am using Plasma 5.113.5, Frameworks 5.49.0 from Debian Testing

**Comment by RomanHargrave** [comment]
Also looks like its getting confused by minimised windows and still partitioning as if they are there

**Comment by RomanHargrave** [comment]
[Demo Video using b7bb220 (I think)](https://www.youtube.com/watch?v=g8Zlq5rkQtU)

Looks like it wont relayout for certain windows

**Comment by RomanHargrave** [comment]
[Demo Video using f7dbbbc](https://youtu.be/OnDAIgc8oNo)

**Comment by RomanHargrave** [comment]
[Demo Video using a5b9290](https://youtu.be/WbwdfMLfwe4)

This makes me wonder if this behaviour has always been present.

**Comment by faho** [comment]
Please run `kwin_x11 --replace` in a terminal and paste the output.

**Comment by RomanHargrave** [comment]
```
Icon theme "ubuntu-mono-dark" not found.
kwin_xkbcommon: XKB: us:63:5: syntax error

kwin_xkbcommon: XKB: Couldn't process include statement for 'us'

kwin_xkbcommon: XKB: Abandoning symbols file "(unnamed)"

kwin_xkbcommon: XKB: Failed to compile xkb_symbols

kwin_xkbcommon: XKB: Failed to compile keymap

Unable to revert mtime: /usr/local/share/fonts
Module 'org.kde.kwin.decoration' does not contain a module identifier directive - it cannot be protected from external registrations.
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 3255, resource id: 56623198, major code: 3 (GetWindowAttributes), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 9 (BadDrawable), sequence: 3256, resource id: 56623198, major code: 14 (GetGeometry), minor code: 0
qml: We're running under KWin 5
qml: We're running under KWin 5
qml: We're running under KWin 5
qml: We're running under KWin 5
qml: We're running under KWin 5
qml: Signal test 1: SUCCESS
qml: Signal test 2: SUCCESS
qml: Testing configuration
qml: Reading floaters
qml: We're running under KWin 5
qml: Starting tiling
qml: Creating HalfLayout
qml: Creating HalfLayout
qml: Creating HalfLayout
qml: Creating HalfLayout
qml: Creating HalfLayout
qml: Creating HalfLayout
qml: Creating HalfLayout
qml: Creating HalfLayout
qml: Creating HalfLayout
qml: Creating HalfLayout
qml: Creating HalfLayout
qml: Creating HalfLayout
qml: Creating HalfLayout
qml: Creating HalfLayout
qml: Creating HalfLayout
qml: Creating HalfLayout
qml: Creating HalfLayout
qml: Creating HalfLayout
qml: Creating HalfLayout
qml: Creating HalfLayout
qml: Creating HalfLayout
qml: Creating HalfLayout
```

**Comment by RomanHargrave** [comment]
@faho it will adjust tiling when Basilisk is moved, now; but I suspect that will inevitably stop happening again.

**Comment by RomanHargrave** [comment]
as an aside, I assume that `,` is the separator for the floaters list in the config dialog?

If that's the case, why is it that those rules are not applying. `systemsettings` should not get tiled at all.

**Comment by faho** [comment]
>as an aside, I assume that , is the separator for the floaters list in the config dialog?

Yes, it is.

>If that's the case, why is it that those rules are not applying. systemsettings should not get tiled at all.

I have no idea. I just checked and it works for me.

Can you confirm that, when you run `xprop` and click on the systemsettings window you get 

>WM_CLASS(STRING) = "systemsettings5", "systemsettings"

-----

Unfortunately that output doesn't show anything wrong. Did the bug happen when that output happened, or did everything work for the moment?

**Comment by RomanHargrave** [comment]
> WM_CLASS(STRING) = "systemsettings5", "systemsettings"

That is the output.

**Comment by faho** [comment]
I'm assuming by "basilisk" you mean http://www.basilisk-browser.org/?

If so... I don't know what to tell you, this works for me with f7dbbbc.

I have frameworks 5.51 and plasma 5.14, but since it used to work when I was using earlier versions and nothing much has really changed, that's unlikely to be the cause.

**Comment by faho** [comment]
I've not been able to reproduce this, so there's no real use in keeping this open. If anyone manages, we can reopen!
