### ISSUE TITLE
Layout with only a certain number of tiles

### ISSUE THREAD

**Issue by githubkusi** [kwin-scripts/kwin-tiling#126]
I'd like to see only two tiles. If a new window is opened, the oldest tile is minimized / removed from the tiles and its place is filled with the new window.

Is this already feasible?

If not, where would be the best starting point to hack this functionality?

**Comment by setzer22** [comment]
Personally, I wouldn't look into implementing this into kwin-tiling, but as a separate kwin script. That's just my opinion, though.

You can take a look at kwin-ministack (https://github.com/faho/kwin-ministack) for some inspiration.

**Comment by githubkusi** [comment]
I think this would be best done as another layout: This allows to resize the two tiles via keyboard or switching to a layout with 3 tiles if needed. All not easily possible by starting from scratch or with kwin-ministack

**Comment by matejdro** [comment]
If this would be done in separate script, how would one switch between those two scripts / ensure no conflicts?

**Comment by faho** [comment]
Sorry, no interest in adding this.
