### ISSUE TITLE
Client's maximized state now scriptable

### ISSUE THREAD

**Issue by laloch** [kwin-scripts/kwin-tiling#130]
Today I have landed [a small change](https://phabricator.kde.org/R108:1d4a9d24f86799b45994c545b054e205f371869f) which adds `Client.setMaximize(v, h)` method to the KWin's scripting interface. In the future this change will allow us for implementing proper Maximized layout and for fixing the havoc that maximized clients can  occasionally bring to the tiling layout. I'll gladly prepare the PRs once the new KWin version gets released. I'm open to discussion and to your suggestions.

**Comment by piotr-dobrogost** [comment]
I believe this would allow to implement change I requested in issue 72 – *Tiled windows should always be set to "unmaximized" state*, yes?

**Comment by laloch** [comment]
Yes, exactly. My version of kwin-tiling does in fact currently behave just like that.

**Comment by piotr-dobrogost** [comment]
Is there any public policy regarding what's exposed to scripts? Why isn't KWin's public API exposed by default?

**Comment by laloch** [comment]
Yeah, I'd like to know too...

**Comment by laloch** [comment]
Closed by #140
