### ISSUE TITLE
Adding/removing a desktop breaks layouts on all desktops

### ISSUE THREAD

**Issue by laloch** [kwin-scripts/kwin-tiling#135]
A picture is worth a thousand words...

Initial state:
![Screenshot_20190327_132519](https://user-images.githubusercontent.com/1336917/55076006-a2e7e880-5094-11e9-808e-93097e34fdca.png)

Desktop added:
![Screenshot_20190327_132555](https://user-images.githubusercontent.com/1336917/55076012-a5e2d900-5094-11e9-96a5-b109de28f16a.png)

**Comment by laloch** [comment]
At first I thought that this could be due to the fact, that my screen's scale factor is 1.4 and that KWin sometimes has the geometry scaling wrong. That didn't prove. The `Client.rect` is just bogus during adding and removing of the desktops.

**Comment by faho** [comment]
I'm not quite sure why we'd do _anything_ to client geometry here?

What signals get fired when you add the desktop?

**Comment by laloch** [comment]
I can see a lot of `Client.geometryShapeChanged` signals before the `workspace.currentDesktopChanged` is triggered. Most probably for each client. At the time the `geometryShapeChanged` gets triggered, the geometry is wrong (not always though). I need yet to check whether it's us who changes the geometry or not.

**Comment by faho** [comment]
This doesn't fire workspace.currentDesktopChanged for me, and I wouldn't assume it should - the current desktop has not changed, after all.

**Comment by laloch** [comment]
Oops, it's `workspace.numberDesktopsChanged` of course. Sorry for the confusion.

**Comment by faho** [comment]
Okay, yeah, that handler has some very suspect code. In particular:

```js
    var newDesktopCount =
        workspace.desktopGridWidth * workspace.desktopGridHeight;
```

I'm pretty sure that's not how that grid works.

**Comment by faho** [comment]
Also this is a great way to crash KWin for me.

**Comment by laloch** [comment]
True, should be
```
var newDesktopCount = workspace.desktops;
```

**Comment by laloch** [comment]
But the geometry is already wrong _before_ the call to `workspace.numberDesktopsChanged` takes place.

**Comment by faho** [comment]
Do you have any patches applied? Which clients are these? I just tried on a desktop with dolphin, konsole and emacs (emacs is _very_ special), and other than it flickering a bit I couldn't see any problem.

Or is this maybe just #111? I don't have gaps typically, though activating them now I see something quite interesting.

**Comment by laloch** [comment]
I'm on current master. The clients are KMail, Kosole, Chrome and VS Code.

**Comment by faho** [comment]
Okay, when I add gaps, I get clients resizing in an infinite loop, because the "tiling_resize" guard no longer works.

**Comment by laloch** [comment]
Arrgh! I did not notice that, because I use Breeze decoration without titlebars. Not gaps.
