### ISSUE TITLE
Problematic default key bindings

### ISSUE THREAD

**Issue by laloch** [kwin-scripts/kwin-tiling#141]
We have some conflicting default key bindings:

Next tiling layout - <kbd>Meta</kbd> + <kbd>PgUp</kbd> is used by KWin for "Maximize Window".
Previous tiling layout - <kbd>Meta</kbd> + <kbd>PgDown</kbd> is used by KWin for "Minimize Window".

Then we have some default shortcuts that do not work on standard US keyboard layout:

Swap with next tile - <kbd>Meta</kbd> + <kbd>Shift</kbd> + <kbd>[</kbd> - there is no such key. It's <kbd>Meta</kbd> + <kbd>{</kbd>.
Swap with previous tile - <kbd>Meta</kbd> + <kbd>Shift</kbd> + <kbd>]</kbd> - there is no such key. It's <kbd>Meta</kbd> + <kbd>}</kbd>.

**Comment by faho** [comment]
Yeah, finding keys never was my strong suit.

Any ideas?

I'd also be okay with dropping some shortcuts, at least by default, though I'm not quite sure what happens with old settings after an upgrade?

**Comment by piotr-dobrogost** [comment]
> Swap with next tile - <kbd>Meta</kbd> + <kbd>Shift</kbd> + <kbd>[</kbd> - there is no such key. It's <kbd>Meta</kbd> + <kbd>{</kbd>.

Recently I hit this and tried looking for a KDE bug pertaining to how shortcuts are presented in the UI. It seems that former representation (involving explicit <kbd>Shift</kbd> key) feels more natural and should be preferred to the latter representation.

**Comment by laloch** [comment]
@faho
>Yeah, finding keys never was my strong suit.
Any ideas?

Yeah, I'm not much of a UX expert either. I have the conflicting keys mapped on <kbd>Meta</kbd> + <kbd>Shift</kbd> + <kbd>PgUp</kbd>.

>I'd also be okay with dropping some shortcuts, at least by default

Yes perhaps, but which ones are those you want to cut off? :)

>though I'm not quite sure what happens with old settings after an upgrade?

My bet would be that the old shortcuts will be preserved. I'll test it later today.

@piotr-dobrogost 
>It seems that former representation (involving explicit <kbd>Shift</kbd> key) feels more natural and should be preferred to the latter representation.

Agreed. But it's not the matter of preference - the problem is that the "nicer" shortcuts just do not work for me with standard US layout.

**Comment by faho** [comment]
>I have the conflicting keys mapped on Meta + Shift + PgUp.

Yeah, that should work (though I have to admit, Meta + PgUP is a _horrible_ shortcut for maximization, and it'd surprise me if anyone actually used it).

>Yes perhaps, but which ones are those you want to cut off? :)

Mostly anything that can be done via KWin's shortcuts should not be in the script, though I've removed most of those already.

"Tile now" is basically a hack that I don't think is all that useful?

Do we need both "move window up/down/left/right" and "swap tile with next/previous"?

 "Toggle Border For All" is basically just "do what KWin does, for all windows", and I don't think it's used often.

**Comment by laloch** [comment]
>though I have to admit, Meta + PgUP is a horrible shortcut for maximization, and it'd surprise me if anyone actually used it.

:)) I do! No kidding. On my NB keyboard it even is Meta + Fn + Up and yet I still use it. 

>"Tile now" is a hack that I don't think is all that useful?

I can imagine that there are users out there who have tiling off by default an only use the script to unclutter their desktops occasionally.

>Do we need both "move window up/down/left/right" and "swap tile with next/previous"?

I do personally only use "move window". "Swap tile" is too confusing to my aging brain.

>"Toggle Border For All" is basically just "do what KWin does, for all windows", and I don't think it's used often.

Can not tell, since I use regular Breeze decorations without title bars. I don't feel any needs to turn them off.

**Comment by faho** [comment]
So, I've just tried to change these, and in the process I reset all shortcuts to the defaults, and it doesn't seem to be registering? I updated the script, restarted kwin, ran kbuildsycoca5 for good measure, and all the tiling shortcuts appear unset? Is this broken again? #79?

This is with kwin 5.15.4.

**Comment by laloch** [comment]
I just tested on KWin 5.15.3. Created a new user, logged in, installed the script, ran kbuildsycoca5 and all the shortcuts are assigned. I'll retest with KWin unstable later today.

**Comment by faho** [comment]
Urgh... it doesn't change the defaults for "known" shortcuts. You need to remove the script, remove inactive shortcuts, then reinstall.

**Comment by laloch** [comment]
Mmm, too bad. There's not much we can do about it though, except for mentioning it in the README.
