### ISSUE TITLE
New clients may be activated behind fullscreen windows

### ISSUE THREAD

**Issue by laloch** [kwin-scripts/kwin-tiling#143]
If I for instance browse the web in a fullscreen browser window, Ctrl+N opens and activates new browser window in background.

**Comment by faho** [comment]
I don't think there's anything we can do, or what do you propose?

Fullscreen windows kinda _have_ to be in front of tiled windows (or they'd be invisible most of the time), that new browser window you start won't be fullscreen, so it should be tiled.

**Comment by laloch** [comment]
Well, I'm not sure about what to do either. That's why I didn't come with a PR, but created an issue instead. Maybe we could (optionally?) toggle the fullscreen state once the fullscreen window get deactivated?

**Comment by faho** [comment]
>Maybe we could (optionally?) toggle the fullscreen state once the fullscreen window get deactivated?

The majority of the time, when I use a fullscreen window, it's either a browser I've set to fullscreen to temporarily view "all" of, or it's a game which is its own little island and while there nothing else matters.

In neither case would I want a new client to become activated, or for the taskbar to pop up. I especially don't want a dialog to pop up in front of my nice fullscreen window. I'll make an exception for volume/brightness indicators. So I'd actually want _the opposite_ of what KWin seems to be doing.

I.e. I don't see how we can improve upon the current behavior, the only thing I believe possible is to make it _worse_ by putting fullscreen windows on the middle layer (neither keepAbove nor keepBelow), but that only works for floating windows anyway.

>Maybe we could (optionally?) toggle the fullscreen state once the fullscreen window get deactivated?

That's kind of a hack. It seems like focus stealing prevention should be at work here - and if I set it to high, I actually don't get activations for _other_ clients, only new browser windows.

**Comment by laloch** [comment]
OK, these are pretty good points. I'm closing this now. Please label it "wontfix".

**Comment by faho** [comment]
>Please label it "wontfix".

I'm pretty sure you can label it as well?

**Comment by laloch** [comment]
Nope, I can't.

**Comment by faho** [comment]
>Nope, I can't.

Huh, seems I needed to add you as a "collaborator" as well. No idea why that's a separate thing, I was under the impression adding someone to an organization would do that.

Now you should be able to!
