### ISSUE TITLE
Where can I find a list of hotkeys?

### ISSUE THREAD

**Issue by rpgdev** [kwin-scripts/kwin-tiling#158]
Where can I find a comprehensive list of all the hotkeys? I'm looking into the entries under "Global shortcuts" but there's no way to identify which hotkeys belong to this script and which belong to others. I updated the script to the latest version by cloning the git repository but I am still unable to see prefixes that identify the shortcuts related to this kwin script.

**Comment by laloch** [comment]
Hi @rpgdev, this sounds strange. On the HEAD of the master branch all the shortcuts should now be prefixed with "TILING:". Did you run `plasmapkg2 --type kwinscript -u .` after updating the sources?

**Comment by rpgdev** [comment]
I did it both ways but still couldn't see it.

**Comment by laloch** [comment]
You may also try to run `kbuildsycoca5`, but I don't really think it's necessary.

**Comment by laloch** [comment]
[README.org](https://github.com/kwin-scripts/kwin-tiling/blob/master/README.org#comprehesive-list-of-keyboard-shorcuts) now lists the supported shortcuts.

**Comment by rpgdev** [comment]
> [README.org](https://github.com/kwin-scripts/kwin-tiling/blob/master/README.org#comprehesive-list-of-keyboard-shorcuts) now lists the supported shortcuts.

Thanks!
