### ISSUE TITLE
Do not resize window when opening a new one and "Automatically group similar windows" is enabled

### ISSUE THREAD

**Issue by piotr-dobrogost** [kwin-scripts/kwin-tiling#16]
When a new instance of already opened app is being run and automatically put as a tab in the window of already running instance – because System Settings|Window Behavior|Advanced|Automatically group similar windows option is enabled – the original window is resized as if the newly opened window was separate from the original one and needed extra screen space.

**Comment by faho** [comment]
Window grouping isn't a thing anymore.
