### ISSUE TITLE
Migrate tiling manager to kwin

### ISSUE THREAD

**Issue by Hi-Angel** [kwin-scripts/kwin-tiling#160]
This is more an informational post, I felt it's important to make it known to kwin-tiling script developers. Feel free to close it.

Recently KDE started accepting goals for 2019 year, and there's a suggestion to add tiling functionality to KWin. Link to the task: https://phabricator.kde.org/T11067

P.S.: the `kkharlamov` user is me. I had to create a throw away account because I couldn't restore my older one — I reported that to admins a few days ago. Hopefully I'll re-subscribe some time later.

**Comment by faho** [comment]
>there's a suggestion to add tiling functionality to KWin.

You do know that KWin used to *have* tiling functionality? And that it was removed because it wasn't maintained?

But, hey, if somebody makes something better and maintains it, sure, why not?

**Comment by Hi-Angel** [comment]
> You do know that KWin used to have tiling functionality? And that it was removed because it wasn't maintained?

I think, that was before Wayland. On X11 there is, like, dozens of tiling window managers. The community resources were just scattered around to a bunch of different projects. I think nowadays such functionality has much greater chance to attract a lot of users.
