### ISSUE TITLE
Emacs is not fully tiled

### ISSUE THREAD

**Issue by Hi-Angel** [kwin-scripts/kwin-tiling#161]
# Steps to reproduce

1. Run `emacs -Q`

## Expected

Emacs window is fully tiled

## Actual

There's a gap between the window and the panel

# Additional information

The size of the gap depends on emacs configuration. Below are 2 screenshots: one is for `emacs -Q`, the other is for emacs with my local configuration — the later has bigger gap.

`emacs -Q`:

![emacs -Q](https://user-images.githubusercontent.com/7935057/59476813-25de3b00-8e5b-11e9-9c9f-afefe0d5ab54.png)

Just `emacs`:
![Screenshot_20190614_041703](https://user-images.githubusercontent.com/7935057/59476842-48705400-8e5b-11e9-9b21-e505308c7296.png)

**Comment by faho** [comment]
Emacs doesn't want to be resized arbitrarily. Set "frame-resize-pixelwise" to t if you want it to.

**Comment by Hi-Angel** [comment]
> Emacs doesn't want to be resized arbitrarily. Set "frame-resize-pixelwise" to t if you want it to.

Thanks, hmm. But i3 does resize it without any gaps.

**Comment by Hi-Angel** [comment]
> Emacs doesn't want to be resized arbitrarily. Set "frame-resize-pixelwise" to t if you want it to.

So, I just tried, setting it — it doesn't have any effect. Both with just `emacs` and `emacs -Q`, when I add a new window to a desktop with emacs forcing emacs to get resized, the gap is still there.

**Comment by Hi-Angel** [comment]
FTR: turned out, emacs can't even be opened to full-screen with acc. hotkey, with disregard to kwin-extension. I reported a bug upstream about that behavior https://bugs.kde.org/show_bug.cgi?id=408746

**Comment by Hi-Angel** [comment]
Ok, let's close this one for now. Turned out, it's Emacs that sets `WM_SIZE_HINTS` to disallow arbitrary resizing, and I don't guess kwin-tiling could override whatever KWin does. This probably requires changes in either in Emacs or KWin.

**Comment by Hi-Angel** [comment]
Fix to Emacs is sent https://debbugs.gnu.org/cgi/bugreport.cgi?bug=36250
