### ISSUE TITLE
Re-enabling kwin-tiling results in windows not getting tiled

### ISSUE THREAD

**Issue by Hi-Angel** [kwin-scripts/kwin-tiling#162]
# Steps to reproduce

1. Make sure `kwin-tiling` is enabled
2. Open `konsole` and `systemsettings5` *(i.e. to have 2 apps on a single screen)*
3. In the opened system settings go to "Kwin scripts", and disable `kwin-tiling`. Press "Apply".
4. Enable `kwin-tiling` back. Press "Apply".
5. Close system settings.

## Expected

The konsole window that is left there is tiled to take the freed space

## Actual

Konsole window stays the same. Moreover: if you close that window, and open a new one — any application — it will take the space that previous master window took instead of being expanded to all free space.

# Versions

kwin: 5.16
kwin-tiling: b4e39ba

**Comment by Hi-Angel** [comment]
I don't know if that relevant, but every time I switch desktop, in `journalctl` I'm getting spammed with these lines:

```
июн 15 21:32:32 constantine-N61Ja kwin_x11[1464]: file:///home/constantine/.local/share/kwin/scripts/kwin-script-tiling/contents/code/tilingmanager.js:967: ReferenceError: workspace is not defined
июн 15 21:32:32 constantine-N61Ja kwin_x11[1464]: file:///home/constantine/.local/share/kwin/scripts/kwin-script-tiling/contents/code/tilingmanager.js:967: ReferenceError: workspace is not defined
июн 15 21:32:36 constantine-N61Ja kwin_x11[1464]: file:///home/constantine/.local/share/kwin/scripts/kwin-script-tiling/contents/code/tilingmanager.js:967: ReferenceError: workspace is not defined
июн 15 21:32:36 constantine-N61Ja kwin_x11[1464]: file:///home/constantine/.local/share/kwin/scripts/kwin-script-tiling/contents/code/tilingmanager.js:967: ReferenceError: workspace is not defined
```

**Comment by Hi-Angel** [comment]
Another oddness: when the bug appears, turns out, I can move the window with kwin-tiling commands "move window left/right/up/down". And the window does move! It looks like kwin-tiling thinks there're some "ghost windows" present. Screenshot:

![Screenshot_20190615_214032](https://user-images.githubusercontent.com/7935057/59555104-3951e900-8fb6-11e9-9ed5-a504588149b7.png)

**Comment by laloch** [comment]
Thanks for reporting @Hi-Angel. I can't, however, reproduce neither of the issues. I'll try to investigate more tomorrow.

**Comment by faho** [comment]
"workspace" is a global object that kwin provides. if it doesn't exist, there's nothing we can do. So it's a kwin bug.

**Comment by laloch** [comment]
@faho, the original report was about re-enabling the script.

**Comment by laloch** [comment]
@Hi-Angel, @faho is right - If your KWin does not provide the `workspace` object, it is definitely broken.

**Comment by faho** [comment]
That may be, but if the error is that kwin's api doesn't exist, all bets
are off. And since that non-existent object is going to be what is causing
the rest,...

David Strobach <notifications@github.com> schrieb am Sa., 15. Juni 2019,
22:03:

**Comment by Hi-Angel** [comment]
So, indeed, I've experimented a bit, and turns out that none of objects that script uses exist. E.g. `KWin`, `options`, `workspace`… I wonder though, why would that happen.

**Comment by Hi-Angel** [comment]
So, in order to get something I could report to kwin devs I tried disabling kwin-tiling, creating a "hello world", and repeating the experiment with it instead. It didn't work, so I enabled kwin-tiling back, and got a similar behavior *(except this time it looked like kwin-tiling wasn't enabled at all, all windows were created "floating")*, and this time `journalctl -f` didn't show any errors from the script.

Oh, well. I don't know, I guess I have to make sure not to re-enable kwin-tiling within a session. Although if I'm going to contribute, this will need to be solved.

**Comment by laloch** [comment]
@Hi-Angel, where does your KWin binary come from? I could give it a try in a VM.

**Comment by Hi-Angel** [comment]
@laloch oh, thanks, it's this one https://www.archlinux.org/packages/extra/x86_64/kwin/

**Comment by laloch** [comment]
OK, so it's the same as the one I currently use. Could you please try to create a fresh user account and repeat the tests from within the fresh user environment?

**Comment by Hi-Angel** [comment]
> OK, so it's the same as the one I currently use. Could you please try to create a fresh user account and repeat the tests from within the fresh user environment?

Just tried, no luck :( Reproducible there as well.

**Comment by laloch** [comment]
That's really weird.
> I tried disabling kwin-tiling, creating a "hello world", and repeating the experiment with it instead. It didn't work, ...

Does the above mean that even the most basic KWin script demo doesn't work?

**Comment by Hi-Angel** [comment]
> That's really weird.
> 
> > I tried disabling kwin-tiling, creating a "hello world", and repeating the experiment with it instead. It didn't work, ...
> 
> Does the above mean that even the most basic KWin script demo doesn't work?

Oh, no, by "didn't work" I meant I couldn't reproduce the problem with the script. I.e. I haven't seen any errors from it in journalctl. But, in that case, neither I saw the errors from the tiling script, even though I could reproduce it with kwin-tiling.

**Comment by faho** [comment]
>I.e. I haven't seen any errors from it in journalctl.

@Hi-Angel I think the default now is to disable these messages. You might have to fiddle with kdebugsettings, specifically the "kwin scripting" setting to get them to appear.

**Comment by Hi-Angel** [comment]
Thanks! So, update:

Turns out, running basic script, which is:

```javascript
workspace.clientMaximizeSet.connect(function(client, h, v) {
    if (h && v) {
        print(client.caption + " is fully maximized");
        throw new Error("Something went wrong");
    } else {
        print(client.caption + " is not maximized");
    }
});
```

…inside an interactive prompt *(which can be ran with `qdbus org.kde.plasmashell /PlasmaShell org.kde.PlasmaShell.showInteractiveKWinConsole`)*.

results in `Error: ReferenceError: workspace is not defined at line 1`.

I tried logging in/out, rebooting — result is always the same. Makes me wondering though, how it's possible that `kwin-tiling` works for me then…

**Comment by Hi-Angel** [comment]
May I ask someone to test the code with the `qdbus org.kde.plasmashell /PlasmaShell org.kde.PlasmaShell.showInteractiveKWinConsole` too? So I could understand if I'm on the right track *(e.g. if it works for you but not for me)*, or is it something else.

**Comment by faho** [comment]
>So I could understand if I'm on the right track (e.g. if it works for you but not for me), or is it something else.

So that works for me, but only if I switch to the "Plasma" tab and then back to "kwin" and *then* run the test.

If I don't do that, it indeed shows the ReferenceError.

**Comment by Hi-Angel** [comment]
Thanks everyone! I reported that upstream https://bugs.kde.org/show_bug.cgi?id=408787

**Comment by laloch** [comment]
> > So I could understand if I'm on the right track (e.g. if it works for you but not for me), or is it something else.
> 
> So that works for me, but only if I switch to the "Plasma" tab and then back to "kwin" and _then_ run the test.
> 
> If I don't do that, it indeed shows the ReferenceError.

That's an old bug in the KWin console itself. I know about it for quite a long time, but I somehow "forgot" to fix it, sorry.
