### ISSUE TITLE
set defaul layout, do not reset layout to default after restart

### ISSUE THREAD

**Issue by ilyam8** [kwin-scripts/kwin-tiling#164]
Hi. I like `i3` layout, i want to have it as default. I dont see such option in the config
![Screenshot_20190623_212433](https://user-images.githubusercontent.com/22274335/59980352-65e0b300-95fd-11e9-909a-58ae5b0ca0df.png)

And it would be nice to remember layour per virtual desktop and not reset it to default after restart.

**Comment by faho** [comment]
In that text area at the bottom, enter: `0:I3`.

**Comment by faho** [comment]
(this should be a list of entries, but unfortunately the only list widget we could use here was removed, so this is the best we can do)

**Comment by ilyam8** [comment]
> 0:I3

`0:I3Layout` works!

Is there an option to remove some layouts from the list? (meta-shift-pgup/pgdown)

**Comment by faho** [comment]
>Is there an option to remove some layouts from the list? (meta-shift-pgup/pgdown)

No, and we have a total of 4 layouts, so I don't think it's all that necessary.
