### ISSUE TITLE
can I change the Meta key?

### ISSUE THREAD

**Issue by jflorian** [kwin-scripts/kwin-tiling#166]
I have a [Kinesis Advantage2 keyboard](https://kinesis-ergo.com/support/advantage2/) and while it's possible to have a Meta key using the _Windows_ layout, I've long ago chosen the _PC _ layout that has a pair of Ctrl and pair of Alt so that the Meta (Windows) key isn't really there.  Remapping won't help as I have no free target keys I can spare.  These habits are very old and won't retrain well.

So, can use something else instead of Meta?  I assume a code change is necessary but would it be simple, impractical, ???

**Comment by laloch** [comment]
Hi @jflorian, all the keyboard shortcuts are configurable via the standard "Global shortcuts" dialog in its "KWin" section. The global shortcuts configuration is accessible either through the "System Settings" tool or from command line: `kcmshell5 keys`.

**Comment by jflorian** [comment]
Why sure enough!  Right there they all are with a big fat `TILING:` prefix.  That's excellent integration so exceeding my expectations that it never occurred to me to look in the most correct location.

Now I just need to determine which I need the absolute most and find some key combos that are free across all my various tools.  (I wish Microsoft in their day of dominance had enforced a keyboard standard that provides a dozen keys that are reserved exclusively for user preferred key bindings.)

**Comment by faho** [comment]
> (I wish Microsoft in their day of dominance had enforced a keyboard standard that provides a dozen keys that are reserved exclusively for user preferred key bindings.)

You know, they did not do *that*, but they used one key in such an annoying manner that you couldn't really pick it for anything else. On other operating systems, that one is basically free.

And since it is known as the "windows" key, it's basically ideal for "window management".

(Yes, that's actually why I always pick that one)
