### ISSUE TITLE
thirds on a 4k monitor

### ISSUE THREAD

**Issue by jflorian** [kwin-scripts/kwin-tiling#167]
I have a rather largish 4k display and having the master always in the left half makes me want to put the display off center so the left side is in front of me and the right side is way over there.  :-)

How hard would it be to go from one full window, to two or more where the master always gets the center slice (~40% of width) with the satellites arrayed to both sides in the remaining space (~20% width each)?  Ever since kwin sprouted _Smart_ window placement and multi-screen support, I've wanted a _Smart, starting at center and working outwards_ mode.  However, one big screen and this awesome kwin-tiling with a centered-ish policy would be worlds better yet.

**Comment by faho** [comment]
Switch the layout?

We have one that spirals, that might be more to your liking? By default this is bound to windows+shift+pgup/pgdown.

Or, since v2.2 you can configure the default split ratio for the default "halflayout".

**Comment by jflorian** [comment]
All of these still make the left side of the screen most prominent.  Imagine a two-lane country road.  I want to "take my half out of the middle".  It only leaves rooms for bikes on either side, but the main work is dead center.  However, with 4k, that's still a LOT of space on either side but the master tile is in a neck-neutral position.

**Comment by laloch** [comment]
I know it's not exactly what you want, but you can create multiple master tiles in Halflayout.

If you could come with some idea and a specification of a layout with the center tile with satellites on both sides, I consider implementing it. I'm maily interested in your idea of dynamic distribution of the space at the sides.

**Comment by jflorian** [comment]
That sounds like a heckuva good deal.  I'm pretty fond of the Half layout but I'll also quickly admit I'm only a few solid days into kwin-tiling.  I've been defeating some old prefs like kwin rules that affect geometry and position.  It's quite a paradigm shift of almost having exactly what I've always wanted "focus follows eyes" to "just keep your eyes over here, that's what where it all happens".  I've not played with multi-master yet and am having a hard time imagining what that means.

As for a new layout spec, let me dwell on that some more.  I may even disable kwin-tiling for a bit a go 100% manual placement to do it non-automated to see if it would really be as usable as I think.  At it's ultimate core though is "center first", somehow.  There may be no such thing that really works in real life usability tests because it would seem there should be some prior art if it's as awesome as I dream.  Then again hi-dpi displays are relatively new.  If we ever get to infinitely sized desktops ala VR, something of this sort will become paramount.

**Comment by laloch** [comment]
>I've not played with multi-master yet and am having a hard time imagining what that means.

The below is a screenshot of my "comms" screen HalfLayout with two master tiles at the left/center.

![Screenshot_20190627_153719-2](https://user-images.githubusercontent.com/1336917/60271262-5362c400-98f2-11e9-9f61-3281aaa2a051.png)

**Comment by jflorian** [comment]
I assume you have a `Default master width` of ~66% here?  The `Default` in that setting's label makes me ask, is there a way to change that on the fly without going back to that dialog?  I didn't see any shortcut keys for modifying it.  Saw those for the _number_ of masters and now I have that gist down, but should there be keys for the master size too?  (I'm not asking for the feature as much as questioning the label.  I don't know if I'd use it.)

**Comment by laloch** [comment]
> I assume you have a `Default master width` of ~66% here?

Almost. It's 64%, but I guess I have resized that particular screen manually.

>The `Default` in that setting's label makes me ask, is there a way to change that on the fly without going back to that dialog? I didn't see any shortcut keys for modifying it.

You can resize the master tile in the same way as you would do with any other tile. Look for "Resize Active Window..." [here](https://github.com/kwin-scripts/kwin-tiling#comprehesive-list-of-keyboard-shorcuts).

**Comment by jflorian** [comment]
> > I assume you have a `Default master width` of ~66% here?
> 
> Almost. It's 64%, but I guess I have resized that particular screen manually.
> 
> > The `Default` in that setting's label makes me ask, is there a way to change that on the fly without going back to that dialog? I didn't see any shortcut keys for modifying it.
> 
> You can resize the master tile in the same way as you would do with any other tile. Look for "Resize Active Window..." [here](https://github.com/kwin-scripts/kwin-tiling#comprehesive-list-of-keyboard-shorcuts).

Oh, duh!  I've been so enamored with the default tile sizing and how much more I can focus on my work rather than window layouts that I hadn't really tried resizing anything.  Or I did and it was so intuitive I hadn't really thought about what was happening.  I did notice that I could drag a window into the master position for a new boss (and have since seen its shortcut key).  Once again, I'm most impressed with how this seems mostly policy on top of what kwin already provided w/o jettisoning lots of kwin features.

**Comment by laloch** [comment]
Yep, all the KWin functionality is mostly present - you can resize and move windows using mouse as usual. The script just extends and modifies KWin's functionality by restricting window placement and position according to the current layout policy and by adding special keyboard shortcuts to control the tiling.

**Comment by laloch** [comment]
Yep, all the KWin functionality is mostly present - you can resize and move windows using mouse as usual. The script just extends and modifies KWin's functionality by restricting window placement and geometry according to the current layout policy and by adding special keyboard shortcuts to control the tiling.

**Comment by faho** [comment]
Okay, this appears to have been answered. I don't think we want yet another layout for this.
