### ISSUE TITLE
Interact with the script via the CLI.

### ISSUE THREAD

**Issue by Kharacternyk** [kwin-scripts/kwin-tiling#171]
I'm trying to get the name of the current layout in my panel. As well as a click way to change it and rotate it. I'm going to use _Command Output_ plasmoid.

Is here any CLI to set and retrieve a layout? I can use `xdotool` command to simulate a shortcuts for changing layout, but I believe there is a more elegant way.

I'm not familiar with the Qt/KDE stack at all.

**Comment by faho** [comment]
This one's quite simple to answer:

>Is here any CLI to set and retrieve a layout?

No. KWin offers nothing in this regard, so the script also can't do it.

**Comment by Kharacternyk** [comment]
Sad. Thanks anyway.
