### ISSUE TITLE
Gaps break shortcuts

### ISSUE THREAD

**Issue by halbGefressen** [kwin-scripts/kwin-tiling#173]
Hi, I just installed the script and edited the config a bit. Before editing everything worked as it should. However, after changing the gap size between windows the up/down shortcuts also resized the focused windows from left to right. Does anyone have an idea why?

**Comment by Kharacternyk** [comment]
Can confirm. If a window doesn't have any space at the top/bottom, trying to resize it in vertical direction changes it's width. In my case, width shrinks by few pixels. I have 8-pixels gaps, if it does matter.

**Comment by faho** [comment]
Duplicate of #111.
