### ISSUE TITLE
Kwin placement for floating mode works like "Zero-Cornered"

### ISSUE THREAD

**Issue by bugworm** [kwin-scripts/kwin-tiling#175]
I have floating mode enabled by default, and kwin has "Smart" window placement:
![image](https://user-images.githubusercontent.com/7214361/62488200-5d6ac300-b7cc-11e9-828f-8271a0e89759.png)
But instead of of this it works like with "Zero-Corneder" placemend (just places all window at the top left corner)

**Comment by faho** [comment]
Yup. Nothing we can do about it - the clients just all appear at 0,0.

**Comment by faho** [comment]
Wait, in floating mode? Okay, lemme check.

**Comment by laloch** [comment]
I can confirm the issue. The initial window placement is "weird" regardless of the "Placement" configuration when tiling is disabled.

**Comment by faho** [comment]
Okay, the first window *is* positioned there, even with the tiling script not running at all.

The second is only if the first is keepBelow, so this looks like a kwin bug to me?

**Comment by faho** [comment]
Or maybe we could set keepBelow later, only when you're actually tiling? Currently it's set when we create the tile, which we also want to do when we're not actively tiling.

>looks like a kwin bug to me?

That's overstating it - it's more likely a kwin *decision* - it'll let it overlap, because there's space there and then *after* it chose the position we set the client to keepBelow (and I don't think we can do it early enough).

**Comment by faho** [comment]
Okay, it's possible to set keepBelow *later*, but for it to be fully usable we'd also have to *unset* keepBelow when deactivating tiling.

**Comment by laloch** [comment]
It's not a (KWin) bug. The `keepBelow` clients are placed in the `BelowLayer` whereas the normal clients are placed in the `NormalLayer`. Since we set `keepBelow` on each new client, KWin thinks the `NormalLayer` is always empty and places new clients at the top left corner.

**Comment by faho** [comment]
>It's not a (KWin) bug

Yeah, I retracted that bit later. It's a valid decision that's only a problem for us because we need keepBelow and can only set it after that decision.

But since dropping new clients at tile 0 isn't that much of a problem, this should work okay-ish now.
