### ISSUE TITLE
Firefox

### ISSUE THREAD

**Issue by fabianskibr** [kwin-scripts/kwin-tiling#176]
Some firefox windows that should be opened as popup are being maximized.

Example: Open the library (where downloads, history, etc. are located).

Images: 
https://imgur.com/a/kfzM18q

**Comment by faho** [comment]
Yes. Unfortunately firefox does not mark these in a way we can detect - they are set to be "normal" intransient windows, with a class of "firefox" (and "Places", where the main window has "Navigator" - neither of which seems reliable enough).

So there isn't anything we can do, sorry.

**Comment by faho** [comment]
I decided to add a workaround for this in 3a47837.
