### ISSUE TITLE
Cycle Rotation bug in i3layout

### ISSUE THREAD

**Issue by e0328eric** [kwin-scripts/kwin-tiling#179]
The only layout, i3layout, has a bug when the cycle rotation is acted.
When the cycle rotation is acted, all windows shrinked in half.
![Screenshot_20190929_191625](https://user-images.githubusercontent.com/55628592/65830788-aaab7280-e2ed-11e9-9b10-4b637c36a83e.png)

**Comment by laloch** [comment]
Hi @e0328eric, thanks for reporting! The I3Layout is not supposed to be rotated in the first place.
The issue should be fixed by aa9e26a30b0be2de910eac38e3847e7fcfe32832.
