### ISSUE TITLE
How to remove old version/upgrade to new version?

### ISSUE THREAD

**Issue by sevku** [kwin-scripts/kwin-tiling#180]
How to remove old version/upgrade to new version?

**Comment by faho** [comment]
I would assume the script downloader in systemsettings also does upgrades?

Alternatively you can download the .kwinscript file and install it either via the "install from file" option or `kpackagetool5 -u /path/to/file`.

**Comment by laloch** [comment]
Also, if you happen to be an Arch Linux user, there's a [kwin-scripts-tiling](https://aur.archlinux.org/packages/kwin-scripts-tiling) package in the AUR.

**Comment by johnZ-cyber** [comment]
> Also, if you happen to be an Arch Linux user, there's a [kwin-scripts-tiling](https://aur.archlinux.org/packages/kwin-scripts-tiling) package in the AUR.

@laloch do you use arch linux? currently the AUR package is without a maintainer. the repository url is also wrong

**Comment by laloch** [comment]
**I** am the maintainer of the AUR package. It's at the last released version (v2.4) and the link points to the KDE store page.

**Comment by johnZ-cyber** [comment]
> **I** am the maintainer of the AUR package. It's at the last released version (v2.4) and the link points to the KDE store page.

sorry i forgot to quote what package it was. this one [kwin-scripts-tiling-git](https://aur.archlinux.org/packages/kwin-scripts-tiling-git/)

**Comment by laloch** [comment]
OK, thanks for reporting. The package is now mine. I'll fix it as soon as possible.

**Comment by laloch** [comment]
@johnZ-cyber, the package should work now. Thanks again for reporting!

**Comment by johnZ-cyber** [comment]
> @johnZ-cyber, the package should work now. Thanks again for reporting!

I thank you for updating the package, it will be very useful!
