### ISSUE TITLE
Can't set specific layout for Desktop 1

### ISSUE THREAD

**Issue by BrdLaw** [kwin-scripts/kwin-tiling#186]
I'm trying to set specific layouts for each virtual desktop, specifically just the spiral layout on each. There isn't any documentation on this available at this point, but the only thing I can remember was a single screenshot with this syntax:

`DesktopName(or DesktopNumber):LayoutName`

so mine is set 

`1:SpiralLayout, 2:SpiralLayout, 3:SpiralLayout, 4:SpiralLayout`

This works for desktops 2,3, and 4, but not 1. Desktop "1" is always set to the dwm-style stack layout. I should also mention that my desktop's are named "1,2,3, and 4" respectively.

**Comment by laloch** [comment]
Hi @BrdLaw, thanks for reporting!
I can confirm the issue. You can work it around by setting your default layout to Spiral: `0:SpiralLayout`.

**Comment by BrdLaw** [comment]
Thanks! That fixes it.
