### ISSUE TITLE
Chromium tab drag-and-drop is forced to tile (while being dragged) on a screen with tiling turned off

### ISSUE THREAD

**Issue by Eximius** [kwin-scripts/kwin-tiling#188]
Not sure why this happens.

Would be awesome to make chromium tab drag-and-drop in the excluded window list, but I do not see any identifying xorg properties which could be used.

Also, this issue: reduce, reuse.

**Comment by faho** [comment]
This never even triggers KWin's movement code, so there's apparently nothing we can do. Sorry!
