### ISSUE TITLE
Shading and unshading windows don't work as expected

### ISSUE THREAD

**Issue by ilkerhk** [kwin-scripts/kwin-tiling#189]
Hello,
When I shade a window (located in the lower part of the screen), after shading completed the remaining windows do not resize (I can see the desktop under the previously shaded window). 
It works fine if the window is on the upper part. 

Also, unshading a window (located upper or lower) does not work as expected. It unshades but height of the window becomes almost 0.  

thanks in advance.

**Comment by faho** [comment]
Yeah, the resizing code isn't smart enough to figure out that it needs to move this.

We could also just untile shaded clients, like fullscreened ones.
