### ISSUE TITLE
Wayland Segfault when dragging windows

### ISSUE THREAD

**Issue by TRPB** [kwin-scripts/kwin-tiling#191]
Steps to reproduce:

1) Using Wayland and the tiling extension, open two sublime text windows
2) Drag one of them around the screen for a few seconds

kwin_wayland segfaults:

> [30231.105226] kwin_wayland[178785]: segfault at 28 ip 00007f6e247a360c sp 00007fff363b4ee0 error 4 in libQt5Qml.so.5.14.0[7f6e2479d000+307000]

It doesn't have to be sublime text, but it seems to be the easiest way to reproduce the issue.

It's definitely the scripting engine or the tiling extension because without tiling enabled, I can drag the window around seemingly indefinitely before anything breaks.

**Comment by faho** [comment]
Crashes are always kwin's fault.
