### ISSUE TITLE
Stetch window across multiple monitors?

### ISSUE THREAD

**Issue by ghassanyounes** [kwin-scripts/kwin-tiling#198]
I currently have a multimonitor setup and cannot figure out how to stretch a window across multiple monitors. I cannot find a keybind for it and cannot manually stretch it to another monitor.

**Comment by faho** [comment]
There isn't a keybinding.

The basic model we have is that windows are on exactly one monitor at a time, and KWin doesn't expose enough information to us to do anything else (in particular the monitor layout is unavailable).

So if you want to stretch a window across monitors, you'll have to let it float, everything else is, as it stands, unfixable.
