### ISSUE TITLE
Kwin crashes when moving or opening windows

### ISSUE THREAD

**Issue by Nano-Ocelot** [kwin-scripts/kwin-tiling#201]
Occasionally Kwin will crash when moving or opening a window while this script is active. 
Here's a bug report for it as well. This issue started randomly around a month or so ago. https://bugs.kde.org/show_bug.cgi?id=416826

**Comment by faho** [comment]
Yes. This is an upstream issue (crashes are by definition) and there is nothing to be done in the script.
