### ISSUE TITLE
Resizing window with keyboard

### ISSUE THREAD

**Issue by lucaspar** [kwin-scripts/kwin-tiling#203]
I believe this was a change of functionality, but I can't find a Kwin Tiling shortcut to resize the active window. I put what I believe to be the old shortcut in the screenshot below.

![kwin](https://user-images.githubusercontent.com/7535699/77964463-14acd080-72ad-11ea-9e73-030f183dd058.png)

The readme reads "Resize windows to resize the tiles" - which works, but is there a way to do this using the keyboard only?

**Comment by laloch** [comment]
Hi @lucaspar, the two highlighted shortcuts don't really belong to kwin-tiling. The TILING-prefixed, however, do. You can use <kbd>Meta</kbd> + <kbd>Alt</kbd> + <kbd>{H, J, K, L}</kbd> keys to resize the active tile.
There's also a [list](https://github.com/kwin-scripts/kwin-tiling#comprehensive-list-of-keyboard-shorcuts) of shortcuts and their default bindings.

**Comment by lucaspar** [comment]
My bad, I just noticed I used this in the past https://github.com/lingtjien/Grid-Tiling-Kwin

Thanks
