### ISSUE TITLE
Conky layers are tiled like regular windows

### ISSUE THREAD

**Issue by RespawnMe** [kwin-scripts/kwin-tiling#204]
Is there a way to exclude these from tiling?
Plasma 5.18.4

**Comment by faho** [comment]
I can't reproduce this.

But anyway, to exclude them you'd do the same thing you always do - figure out the window class and add it to the exclusion list in the config. I find the easiest way is to execute `xprop` in a terminal and click the window you want, then check the line that says `WM_CLASS(STRING)`. That *second* string is the one you want, tho in this case I get:

```
WM_CLASS(STRING) = "Conky", "Conky"
```

which means they're the same anyway.

**Comment by RespawnMe** [comment]
Many thanks mate, i will test this.
