### ISSUE TITLE
Move Windows to specific desktop

### ISSUE THREAD

**Issue by twnaing** [kwin-scripts/kwin-tiling#205]
I saw "Move Windows To New Desktop" (Meta+Shift+D).

Is this possible at this moment to send current focused windows to specific desktop (let's say desktop 3)? 

If not, is there a plan to implement the feature? (This might not be sensible if user set it to remove inactive desktop.)

**Comment by laloch** [comment]
Hi @twnaing, I believe that what you're asking for is "Window to Desktop {1..20}" shortcut. That functionality is already built into KWin itself. Head on to "Global Shortcuts" system settings module, select "KWin" component and look for "Window to Desktop" shortcuts in the right-hand list of available shortcuts.
