### ISSUE TITLE
kwin-tiling seems to break with kwin 5.18.5

### ISSUE THREAD

**Issue by gerion0** [kwin-scripts/kwin-tiling#206]
Yesterday I updated my kwin from 5.18.4.1 to 5.18.5 and it seems that this broke kwin-tiling.

Currently the problem is, that all windows are started with window bars and the full screen size. I can "tile" them manually with Meta-F, then the window bar disappears, but there is no tiling. All windows are full sized.

However, when I switch the tiling layout, the script show a little notification what layout is activated now, but of course this has not any effect, this the tiling is missing.

Can I debug this myself? Can I somehow see, what functions of kwin-tiling are executed by kwin?

**Comment by laloch** [comment]
Hi @gerion0, thanks for reporting.
I do myself run kwin_x11 5.18.5 for some time without any (new) issues. Does running `journalctl /usr/bin/kwin_x11` reveal any clues regarding your problem?

**Comment by gerion0** [comment]
```
% kwin_x11 --replace
kwin_xkbcommon: XKB: couldn't find a Compose file for locale "de_DE.UTF8"

Fontconfig error: failed reading config file
Fontconfig error: Cannot load config file "infinality/conf.d"
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 1975, resource id: 140509215, major code: 3 (GetWindowAttributes), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 9 (BadDrawable), sequence: 1976, resource id: 140509215, major code: 14 (GetGeometry), minor code: 0
kwin_core: Compositing is not possible
qml: We're running under KWin 5
qml: We're running under KWin 5
qml: We're running under KWin 5
qml: We're running under KWin 5
qml: We're running under KWin 5
qml: Signal test 1: SUCCESS
qml: Signal test 2: SUCCESS
qml: Testing configuration
qml: Reading floaters
qml: We're running under KWin 5
qml: Starting tiling
qml: Creating HalfLayout
qml: Creating HalfLayout
qml: Creating HalfLayout
qml: Creating HalfLayout
qml: Creating HalfLayout
qml: Creating HalfLayout
qml: Creating HalfLayout
qml: Creating HalfLayout
qml: Creating HalfLayout
qml: Creating HalfLayout
```
I'm pretty sure some of the "BadWindow" entries belong to Mumble. The Mumble window is not even shown and triggers a lot of these errors. However, when I quit Mumble and open a normal terminal window, I also get some of these:
```
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 2399, resource id: 132120622, major code: 3 (GetWindowAttributes), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 9 (BadDrawable), sequence: 2400, resource id: 132120622, major code: 14 (GetGeometry), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 2940, resource id: 134217742, major code: 15 (QueryTree), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 2945, resource id: 134217742, major code: 18 (ChangeProperty), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 3026, resource id: 123731982, major code: 15 (QueryTree), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 3031, resource id: 123731982, major code: 18 (ChangeProperty), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 3356, resource id: 123731982, major code: 15 (QueryTree), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 3361, resource id: 123731982, major code: 18 (ChangeProperty), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 3686, resource id: 123731982, major code: 15 (QueryTree), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 3691, resource id: 123731982, major code: 18 (ChangeProperty), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 5415, resource id: 123731982, major code: 15 (QueryTree), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 5420, resource id: 123731982, major code: 18 (ChangeProperty), minor code: 0
qml: No rectangle okular 144703494
qml: No rectangle okular 144703494
qml: No rectangle okular 144703494
qml: No rectangle okular 144703494
qml: No rectangle okular 144703494
qml: No rectangle okular 144703494
qml: No rectangle okular 144703494
qml: No rectangle okular 144703494
qml: No rectangle okular 144703494
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 7036, resource id: 144703536, major code: 18 (ChangeProperty), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 7040, resource id: 14680193, major code: 18 (ChangeProperty), minor code: 0
```

Interestingly I got a step further to get the old behaviour. The above bug description seems not to be always true. I found out, that sometimes pressing the key combination for "Toggle Tiling" triggers the above behaviour when pressing "Toggle Floating" after that. In other words:

- Status: Tiling off
  - Pressing "Toggle Floating" hides the window bar and border but does not change the reposition of the window.
- Status: Tiling on
  - Pressing "Toggle Floating" hides the window bar and border and tiles the window (reposition it and change the size of the other tiled windows).
- "Tiling on" and "Tiling off" can be switched by pressing "Toggle Tiling".

However, even when "Tiling on" is activated, a new window is currently always untiled. I need to press "Toggle Floating" to enable Tiling for this window. In the script settings, tiling is activated by default.

When restarting kwin_x11 the behaviour is sometimes the one described in my first post, sometimes the one described in this post. I'm a little bit confused.

I will downgrade again. Maybe this fixes the error.

**Comment by gerion0** [comment]
Ok, the downgrade did not solved anything. I will try to find it out, what the real reason is (was a bigger update yesterday, maybe some other software broke).

**Comment by michel-zedler** [comment]
Same issue: new windows float freely when I expect them to snap into a new tile.

` kwin_x11[114347]: file:///home/me/.local/share/kwin/scripts/kwin-script-tiling/contents/code/tilelist.js:77: ReferenceError: options is not defined`
in journalctl /usr/bin/kwin_x11 when a new window opens.

I am running kwin-tiling (origin/master at 74ccaa97558ae6635d0afbfc50bbbb098b27917a) on kwin 5.18.5-1.

My current workaround is to snap them in by hitting the "Toogle Floating" shortcut. 
They will also snap in when switching away from the current virtual desktop and back.

**Comment by faho** [comment]
These issues aren't the same.

> ReferenceError: options is not defined

This means your kwin is broken, please check if there's an additional package you need to enable qml scripts.

Anyway, it's worked around by 2f63ff3b4166211e11fac63fdf4029ba155d6f20 removing that call.

----------------

The other issue is probably that you're running wayland, which... tbh is still quite bad with KWin.

**Comment by michel-zedler** [comment]
Hi @faho, 

meanwhile on kwin 5.19.4-1, I checked out the latest origin/master (includes 2f63ff3), upgraded kwin-tiling (using
`plasmapkg2 --type kwinscript -u .`) - and boy am I happy to have kwin-tiling back!

You were also right about the disabled compositor - it had disabled after repeated crashes.

Hearty thanks for your help and the work you have put into this project!

**Comment by faho** [comment]
Yeah nobody's managed to figure this one out, closing.
