### ISSUE TITLE
what's the difference between i3layout and BladeLayout?

### ISSUE THREAD

**Issue by mekatum** [kwin-scripts/kwin-tiling#208]
Hi all! Thanks you for your work!
Is there any way to do layout without master window? For example, each of 4 window placed on 1/4 of screen.

And what's the difference between `i3layout` and `BladeLayout`? In my fedora 31 with `plasmashell 5.17.5` and `kf5-config Qt: 5.13.2 KDE Frameworks: 5.68.0 kf5-config: 1.0` they look the same. Tiling script 2.4.0

**Comment by laloch** [comment]
Hi @mekatum,
> Is there any way to do layout without master window? For example, each of 4 window placed on 1/4 of screen.

I think that's already been requested (#168). There's currently no grid layout implemented.
> And what's the difference between `i3layout` and `BladeLayout`? In my fedora 31 with `plasmashell 5.17.5` and `kf5-config Qt: 5.13.2 KDE Frameworks: 5.68.0 kf5-config: 1.0` they look the same. Tiling script 2.4.0

Blade layout divides the screen space evenly between tiles. In i3 layout, you control the direction of the splits manually. You need to first bind the i3-specific keyboard shortcuts to make proper use of it.

**Comment by faho** [comment]
However the i3 layout happens to behave like the blade layout when you don't do anything.

I think we could actually remove the BladeLayout because of this?

**Comment by laloch** [comment]
> However the i3 layout happens to behave like the blade layout when you don't do anything.

Except for rotation. I did not implement rotation for i3 layout, because a) I didn't really see a point in doing so and b) I didn't know how.

**Comment by faho** [comment]
Ah, yeah, I can see how that might be tough.

**Comment by mekatum** [comment]
> I think that's already been requested (#168). There's currently no grid layout implemented.
Thank you for you replies.

If I understand correctly, you need help developing grid layout, not no KWin behavior?

**Comment by laloch** [comment]
> If I understand correctly, you need help developing grid layout

A PR would be very welcome. There are, however, some unanswered design questions. For instance, let's say your grid layout is 2x2 tiles, what should happen when you open fifth window on the same screen?

> ,not no KWin behavior?

I don't understand.
