### ISSUE TITLE
Wayland Support

### ISSUE THREAD

**Issue by WillPower3309** [kwin-scripts/kwin-tiling#210]
Currently the script works with tiling xwayland windows under wayland, however native wayland windows do not tile. When enabling the script in wayland, all windows tile (including wayland native windows), however subsequent wayland windows do not tile. This is especially problematic as all plasma windows are wayland native.

**Comment by faho** [comment]
Yeah, that's up to upstream, there's literally nothing for the script to do.

There is an open bug.

**Comment by faho** [comment]
https://bugs.kde.org/show_bug.cgi?id=401309, including https://phabricator.kde.org/D17097, which is stuck in review because someone has security concerns (for some reason).

**Comment by laloch** [comment]
Nope, it was already merged in https://phabricator.kde.org/R108:4bbef8d128ce339b4fa08816780c42c40bdd909e. Basic functionality should be there since Plasma 5.17.

**Comment by faho** [comment]
One of these days I'll figure out how to read phabricator's web interface.

**Comment by WillPower3309** [comment]
Thanks for the fast response guys! Does this mean that the script should work since the request to emit clientAdded on wayland clients was merged?

**Comment by laloch** [comment]
Yes, it should work and I believe @TRPB to have some fixes to make the script (more) usable on Wayland.

**Comment by WillPower3309** [comment]
The behavior i described exists on the master branch of the repo running in the newest version of plasma wayland

**Comment by WillPower3309** [comment]
On a wayland session in Plasma 5.19, wayland clients are not tiled and spawn in as floating clients

**Comment by WillPower3309** [comment]
To clarify, on plasma 5.19, wayland clients are still being spawned in as floating clients. Does the repo still need to be updated to support wayland (in which case I'd be happy to investigate and provide a PR), or is there an issue with my setup?
