### ISSUE TITLE
Tiles floating latte panel popups

### ISSUE THREAD

**Issue by WillPower3309** [kwin-scripts/kwin-tiling#211]
![](https://i.imgur.com/lS2F3eL.jpg)

As you can see in the image, the windows tile to allow space for the popup but since it is floating the result is a weird layout

**Comment by laloch** [comment]
Hi @WillPower3309, is this on Wayland? It is a known issue on Wayland.

**Comment by WillPower3309** [comment]
@laloch nope, running in X!

**Comment by laloch** [comment]
Could you try to pin that popup, run `xprop | grep WM_CLASS` click it and post the result?

**Comment by WillPower3309** [comment]
Yessir!
`WM_CLASS(STRING) = "latte-dock", "lattedock"`

**Comment by laloch** [comment]
Thanks! You can prevent the issue by adding "latte-dock" to the "Excluded window classes" list in the script's configuration dialog.

**Comment by WillPower3309** [comment]
Ah, much appreciated. Thanks! I love the work yall do here

**Comment by laloch** [comment]
Did that help? If so, I'll open a PR to make it default.

**Comment by WillPower3309** [comment]
Update, it actually didnt solve the issue. I also tried lattedock, and both with and without quotation marks.

**Comment by laloch** [comment]
You need to restart KWin (`kwin_x11 --replace`) in order to make the config change effective. It's one of the known upstream issues (sigh).

**Comment by WillPower3309** [comment]
Yep, problem still exists

**Comment by laloch** [comment]
I can confirm that adding `lattedock` (without quotation marks) does fix the issue for me.

**Comment by laloch** [comment]
@WillPower3309, the issue should be fixed on master/HEAD.
