### ISSUE TITLE
Spotify opens floating, must be manually tiled via shortcuts

### ISSUE THREAD

**Issue by WillPower3309** [kwin-scripts/kwin-tiling#213]
As the title suggests, spotify wont tile at launch

**Comment by faho** [comment]
Yeah, spotify starts with an empty window class.

God that's broken.

**Comment by faho** [comment]
We ignore empty window classes on purpose, so this is not a bug.

**Comment by laloch** [comment]
Hi @WillPower3309, that bug is known to Spotify developers for years. There is nothing we can do about it.
See [this Spotify Community thread](https://community.spotify.com/t5/Desktop-Linux/WM-CLASS-window-property-on-Linux/td-p/1247042) for details and for some suggested workarounds.
