### ISSUE TITLE
Spiral tiling with overlap

### ISSUE THREAD

**Issue by auwsom** [kwin-scripts/kwin-tiling#214]
Hello, this script is a long desired addition to KDE and Kubuntu. (before I forget, is there a way to tile only a set of the same application windows? For example, stack Chrome windows, but autotile Konsole terminal windows?)

Im hoping other people are wishing there was more options for setting the 'overlap' of the tiles. Basically a negative 'gap' setting. Picture a rectangular Ven Diagram. ..well here's one, but I was thinking all windows would stretch to the corners (as tiling does, with more of a stacking overlap in the center): 
![image](https://user-images.githubusercontent.com/25093612/86053241-0df93b00-ba0d-11ea-8ade-c6b83afd55f0.png)

Maybe there is a 'KWin Stacking Script' I'm unaware of, but I think kwin-tiling is the closest yet. Please let me know if it could be modified to do this. sbergeron's comment from Jul 5 2019 this thread on a KDE tiling window manager (https://phabricator.kde.org/T11067) sums this blended functionality up well.

One step further, would be a 'spiral cascade' where each window spirals around the back of the top window. You can see from my drawing each window is accessible to click on with mouse, by more so than the usual title bar width cascade. 
![Spiral Tile](https://user-images.githubusercontent.com/25093612/86057858-c5458000-ba14-11ea-97ff-d598c96e809a.png)
In fact, to get back to more of the tiling spectrum, each window edge should touch the screen edge, only being shrunk when a new level of windows is added. While this may obscure the front windows, when rear ones are select, the Z order of last used should keep recent ones accessible. 
![Spiral Tiling 2](https://user-images.githubusercontent.com/25093612/86059197-1f474500-ba17-11ea-9dd3-e7917c9650a1.png)
There are two ways to deal with that obscuring, but I would say after 8 window, minimizing some (or a second desktop) is probably best. The first is to use the 'spiral cascade' on the second (and third, plus) levels. The other way is that in theory, each small rectangle, cyan in the above drawing, could have a button that shows through transparently, these themselves could spiral all the way down. Probably turtles would be the ideal icon here ;)!

**Comment by auwsom** [comment]
For the sake of completeness, here is a drawing version with minimal overlap, more true to the title of Spiral Tiling. The key parameter here is the amount of overlap, or 'negative gap'. I would think that simply allowing the already defined gap parameter to go negative (if the current logic could handle that) would allow users a much wider range of uses.  

![Spiral Tiling 3](https://user-images.githubusercontent.com/25093612/86061541-d3e36580-ba1b-11ea-8470-da93f5104ff5.png)

**Comment by faho** [comment]
This might look nice, but it's mostly useless - the overlap removes most of the utility of tiling in the first place, so you can just tile the windows.

Sorry, but I don't think we're interested.

**Comment by auwsom** [comment]
Hi Fabian,

Usefulness is in the eye of the beholder. I realize this is not 'pure'
tiling, but it is the closest to a desired functionality of mine and
others currently
I believe, and so a fitting place to ask.

No worries, hopefully others that are interested will find this, and it
might encourage your project to expand the functionality or a fork to be
started.

The other purpose was to ask for your expertise on a possible fork. Is
there a setting for the gap spacing between tiles as I've seen on a couple
of other forks? If so, could you point me toward it? And would the code
logic be able to handle a negative value for overlap?

Thank you
