### ISSUE TITLE
Unable to toggle tiling on/off. Remains on.

### ISSUE THREAD

**Issue by bassamanator** [kwin-scripts/kwin-tiling#215]
On Manjaro I'm unable to turn tiling off by using meta-shift-F11. Windows continue to snap into place.

Nice script.

**Comment by faho** [comment]
Works for me.

Please check that you have actually bound meta-shift-f11

**Comment by bassamanator** [comment]
![image](https://user-images.githubusercontent.com/61985779/86518318-e6381780-bdfe-11ea-99d8-386df3c9bd3e.png)
You can see the shortcut in the pic above. Also, when I activate the shortcut, *something* happens. I am sort of able to move the windows around, however, they *tend* to snap back into some place (I can't control it really). Also, some windows will be above others when I don't want them to be nor have I told them to be 'Keep above others'.

My understanding is this: when I enable this script (via m-s-f11), the windows should tile themselves on my screen (the windows also reposition themselves if I move them around). When I disable this script (via m-s-f11) I should be able to move the windows around freely, without them snapping into place. Is this correct?

**Comment by llabusch93** [comment]
Hello @faho 

I have the exact same issue like @bassamanator and I am also on Manjaro. Any progress on this, can I support the debugging by something?

**Comment by faho** [comment]
I'm assuming this is another manifestation of #218 - we resized floating windows under some circumstances.
