### ISSUE TITLE
Maximized layout breaks when new window opens

### ISSUE THREAD

**Issue by matejdro** [kwin-scripts/kwin-tiling#216]
1. Have couple of windows open on the screen
2. Maximize one of them - all windows get maximized and you can alt tab between them
3. Open new window

Bug: All windows will get un-maximized and return to the regular tile layout.

**Comment by faho** [comment]
It's not a maximized *layout*. The idea is that you maximize a window to take a closer look at it but otherwise go on.

This is working as intended.

**Comment by matejdro** [comment]
Would you be willing to turn that temporary state into layout? Can I create another issue for feature request?
