### ISSUE TITLE
Pager widget still shows old layout when switching to maximized mode

### ISSUE THREAD

**Issue by matejdro** [kwin-scripts/kwin-tiling#217]
1. Have Pager widget displayed somewhere on the screen
2. Have couple of windows open on the screen - they should be tiled properly
2. Maximize one of them - all windows get maximized and you can alt tab between them
3. Take a look at window outlines in Pager widget

Bug: Only the window that you maximized manually is shown up as maximized in that layout, others are still shown in their old tiled layout

I realize that this issue could be from both kwin tiling and Pager, but Pager displays maximized windows properly if I disable the script and maximize them manually. Maybe script needs to set some kind of flag?

**Comment by faho** [comment]
They *are* in their old layout. Like I said in #216, "maximized" isn't a layout. It's a temporary state.
