### ISSUE TITLE
Option to keep floating windows on top

### ISSUE THREAD

**Issue by addy419** [kwin-scripts/kwin-tiling#218]
when tiling is enabled by default and you change current window to floating, disable keep below and re-enable it again when tiled. this setting can be optional.

**Comment by faho** [comment]
https://github.com/kwin-scripts/kwin-tiling/blob/master/contents/code/tilelist.js#L335

This already happens.

**Comment by addy419** [comment]
My tiled windows overlap floating windows. This happens only happens when I toggle floating, not when I ignore it or when tile isn't set bt default. I am using the latest version from master

**Comment by addy419** [comment]
@faho to reproduce this, open multiple windows, then use TILING toggle floating shortcut to float a particular window, then click on one of the tiled windows behind this window. It'll go below it.

**Comment by faho** [comment]
Yeah, that's what KWin does. AFAIK there's no way around that. We reset keepBelow/keepAbove, that's all we can do.

**Comment by addy419** [comment]
@faho It does work when I add the window to ignore list? Why doesn't KWin interefere then?

**Comment by addy419** [comment]
> I rechecked the window and keep below others is still enabled when I toggle floating

**Comment by faho** [comment]
Yeah, something's borken here. Lemme check.

**Comment by faho** [comment]
Yeah, for some reason we resized the client after its tile was removed, which re-set keepBelow.

**Comment by addy419** [comment]
I was trying to narrow this down, but couldn't find it. Thanks for the fix, works great now👍
