### ISSUE TITLE
Formal Release of Version 2.4

### ISSUE THREAD

**Issue by JKomoroski** [kwin-scripts/kwin-tiling#220]
Please do a github release of the latest version so package maintainers can easily update. I see tags for 2.2 - 2.4 but the releases page only shows 2.1.

Thanks!

**Comment by faho** [comment]
Blergh.

Yeah, it used to be that github just used tags for this.

Okay, lemme add the latest.

Also note that I can't recommend using packages - in my experience they've never really worked well.

**Comment by faho** [comment]
Yeah, done.
