### ISSUE TITLE
Thunderbird reply window

### ISSUE THREAD

**Issue by fabianski7** [kwin-scripts/kwin-tiling#221]
Is there any way to disable the script for thunderbird's compose email window? 
As I understand it, TB runs a single process, so putting the thunderbird class on the exclude list would exclude the whole client.

**Comment by laloch** [comment]
Hi @fabianski7, unless `xprop | grep WM_CLASS` shows different string for the composer window from the main window, there's, i think, nothing we can do about it right now, since we only match according to the WM_CLASS.

**Comment by fabianski7** [comment]
it seems that there are two classes.
```
$ xprop | grep WM_CLASS
WM_CLASS(STRING) = "Msgcompose", "Thunderbird"
```
I tried `Msgcompose` and `Msgcompose Thunderbird`, none of the options worked

**Comment by laloch** [comment]
@fabianski7, does #222 solve the issue for you?

**Comment by fabianski7** [comment]
that solves the problem. thanks!
