### ISSUE TITLE
Sudden frequent Kwin crashes when resizing splits in Spiral Mode

### ISSUE THREAD

**Issue by wd5gnr** [kwin-scripts/kwin-tiling#225]
Since upgrading Neon to 20.04, I've had a vexing problem (and just updated to latest GitHub of the script and restarted X). I use the Spiral layout by default. When I try to move the split it works some times. Other times, Kwin crashes and restarts. All my windows surface and it -- usually -- recovers. Sometimes it dies multiple times in a row.

Hard to pin down because it does not always happen. Not sure how to pull logs related to that although I suppose I could run Kwin_x11 from a console to get the messages from it.

Anyone else noticing this behavior?

**Comment by faho** [comment]
Yeah, it's a bug in Qt, fixed in 5.15.1 (while Ubuntu 20.04 ships with Qt 5.12.something)

A workaround is to set the QV4_FORCE_INTERPRETER to 1 (see also https://community.kde.org/KWin/Environment_Variables)

**Comment by wd5gnr** [comment]
Thank you!
