### ISSUE TITLE
Focus next/previous tile across screen

### ISSUE THREAD

**Issue by Zaraka** [kwin-scripts/kwin-tiling#227]
I have a total of 3 windows on a single desktop, 2 of them are on screen A, the last one is one screen B. Screen A and B are next to each other.

When triggering shortcut Focus next/previous tile I would like to be able to focus from window 1 to window 2 and then to window 3. But It looks like I'm locked on a single screen meaning that I can't focus from window 2 to window 3.

**Comment by laloch** [comment]
Hi @Zaraka, we recommend using Plasma task switcher (Settings/Window Management/Task Switcher) and it's key bindings. You can customize the scope (Activity/Desktop/Screen) of considered windows there.

**Comment by Zaraka** [comment]
@laloch You are right. I've looked into the shortcuts more and it looks like Plasma 5.19 supports the exact behavior I was looking for.
![image](https://user-images.githubusercontent.com/1270094/97625427-c7523680-1a28-11eb-9e31-804c39973bd7.png)

**Comment by TrdNugget** [comment]
thank you
