### ISSUE TITLE
uninstalling

### ISSUE THREAD

**Issue by filippo-ferrando** [kwin-scripts/kwin-tiling#228]
hey, i have installed this script and i'm very happy with it, but if i want to fully remove it, how do i do it?
Thanks

**Comment by faho** [comment]
In current KWin versions there's a delete button in the settings menu, so just click that.

I recall that it wasn't always there, in that case you'd have to run something like `kpackagetool5 -r kwin-script-tiling` in a terminal.

**Comment by filippo-ferrando** [comment]
Thank you a lot!!

Il mer 4 nov 2020, 17:02 Fabian Homborg <notifications@github.com> ha
scritto:
