### ISSUE TITLE
Bug: Menus are displayed in a separate window

### ISSUE THREAD

**Issue by eclipseo** [kwin-scripts/kwin-tiling#229]
OS: Fedora 33
Plasma: 5.19.5
KDO Frameworks: 5.75.0

I have global menus on the title bar enabled and when I click on it, the menu appear as a separate window.

**Comment by faho** [comment]
This means the menus aren't correctly marked as such, so you'll have to add them as excluded manually.

There's no way for us to detect this (that's why they should be marked as menus), sorry!

**Comment by laloch** [comment]
Hi @eclipseo, thanks for reporting. This is most probably an upstream bug, that should be reported upstream.

**Comment by laloch** [comment]
@eclipseo, just FYI, I'm currently on Plasma 5.20.2 and global menus work just fine for me. See here:
![Screenshot_20201106_184526](https://user-images.githubusercontent.com/1336917/98397838-431f3500-2060-11eb-8c21-2f56a5970ced.png)

**Comment by eclipseo** [comment]
> @eclipseo, just FYI, I'm currently on Plasma 5.20.2 and global menus work just fine for me. See here:
> ![Screenshot_20201106_184526](https://user-images.githubusercontent.com/1336917/98397838-431f3500-2060-11eb-8c21-2f56a5970ced.png)

Global works but I'm referring to tittle bar ones.
