### ISSUE TITLE
Ignore by title?

### ISSUE THREAD

**Issue by schemar** [kwin-scripts/kwin-tiling#230]
Hey there, is it possible to ignore a window by its title instead of its class?

The reason I am asking is misbehavior of slack. When you are in a call and focus another window, slack opens a „mini panel“, which has the default type and the same class as the main window. 

If I could ignore by window title, I could ignore the mini panel. It always has the same title „Slack | mini panel“.

Alternatively, I could live with an option to float slack windows when they open, I could then unfloat the main window once after startup, but I don’t have to repeatedly float the mini panel in every call every time I change focus.
Unfortunately, I cannot add „slack“ to the list of ignored classes, as this forbids me to unfloat the main window.

Anything I can do?

Thank you for your great work and help.

**Comment by schemar** [comment]
In the worst case, could I completely remove the mini panel with kwin settings for windows?

**Comment by tabroughton** [comment]
@schemar I'm not sure if this helps but I was wanting to get QJackCtl floating and came across this.

https://github.com/kwin-scripts/kwin-tiling/blob/a240b4327892305008525fed96f9f9227c904893/contents/code/ignored.js#L68

in kwinrc under the tiling config I added ```floating=QJackCtl``` which worked - but I see in older commits this section used to be based on just class but now it is also resourcename.

**Comment by schemar** [comment]
Wow, thank you @tabroughton ! 
I don’t need it anymore, though. I switched the Plasma window manager to i3. I’ll close this. Thank you, still!
