### ISSUE TITLE
no tiling and grid layout not defined

### ISSUE THREAD

**Issue by christf** [kwin-scripts/kwin-tiling#232]
after following the instructions from the readme, the extension becomes visible is activated but no tiling happens.
when restarting kwin_x11 the following log appears:

```
qml: Starting tiling
file:///home/christof/.local/share/kwin/scripts/kwin-script-tiling/contents/code/tilingmanager.js:50: ReferenceError: GridLayout is not defined
```

**Comment by faho** [comment]
This works for me, and GridLayout is obviously defined in gridlayout.js, which is also included from tilingmanager.js.

To be clear: You are using the version from git? Which commit is that? `git show` would tell you - the first line says "commit 4b1b17983aa2409cff" or similar.

Which distribution do you use? What's your `kwin_x11 --version`?

**Comment by christf** [comment]
this is debian stable, I was using commit
4b1b17983aa2409cff7e89a40baca5e2f7cdcefb with kwin 5.14.5


--
()  ascii ribbon campaign - against html e-mail
/\  www.asciiribbon.org   - against proprietary attachments

**Comment by faho** [comment]
Ah, okay. I'm guessing this errors because the GridLayout was written by someone with a more up-to-date knowledge of javascript than me, and Debian's.... seasoned Qt can't handle some of the "newer" features - either `let` or tuples (`return [col, row];`).

Sooo we're just gonna have to remove that syntax. Blergh.

**Comment by faho** [comment]
I took a wild guess that it's the tuples - please try a240b43 (a `git pull` and `plasmapkg2 -u /path/to/script` should be enough).
