### ISSUE TITLE
By default, 'Move Window To New Desktop'

### ISSUE THREAD

**Issue by jtagcat** [kwin-scripts/kwin-tiling#234]
..though not floating windows, and (optionally) windows of the same process / title / name / whatever.

There could be a kb shortcut to toggle this behaviour, and whitelist for certain processes. I like to have my browser almost always maximized, unless I need split-screen. On other apps, I need tiling.

**Comment by faho** [comment]
This is easier and nicer to implement as a separate script - at most you'd have to duplicate the list of floating windows.

I'd prefer that to us having to keep yet another list of things when we don't even have a proper widget to let the user enter it anymore.
