### ISSUE TITLE
Persist layout settings

### ISSUE THREAD

**Issue by jnbooth** [kwin-scripts/kwin-tiling#237]
I mostly use HalfLayout, but flipped horizontally by pressing the "cycle rotations" hotkey twice. Unfortunately, if I restart the session or swap to a different layout, the rotation is reset. This means that every time I restart my computer, I have to press "cycle rotations" twice on every desktop. Would it be possible to save those sorts of settings upon change, or at least specify them in some sort of config file?

**Comment by faho** [comment]
Well, there's a settings menu
![Screenshot_20210208_174933](https://user-images.githubusercontent.com/5185367/107252877-0e8f9080-6a36-11eb-9a05-966d4cbdfc86.png)

That bit where it says "layouts for each desktop" is where you configure the layouts for each desktop. Unfortunately kwin doesn't give us much to work with here, so you'll have to do it as a "desktop:layout" string with a comma between each.

**Comment by jnbooth** [comment]
I don't understand how I would use that to tell each desktop to start with HalfLayout rotated twice.

**Comment by faho** [comment]
Ah, okay. Terribly sorry, I misread. That's currently not supported.

And honestly, unless someone sends in a patch it's not going to be supported either - I don't use rotation so I don't have any interest in fiddling with this.
