### ISSUE TITLE
[Feature request] Changing layouts via button on panel AwesomeWM style

### ISSUE THREAD

**Issue by jakubiakdev** [kwin-scripts/kwin-tiling#238]
Example of how AwesomeWM does this:
![image](https://user-images.githubusercontent.com/63729559/107493159-9b009700-6b8d-11eb-8314-4afd8e91603f.png)
[Taken from here](https://github.com/awesomeWM/awesome/issues/1395#issuecomment-272578535)

If you would click the button, the layout style changes. I think it would be more user-friendly, would fit KDE style, and entirely optional

**Comment by faho** [comment]
Thanks, but I don't know of any KWin API we can use here.
