### ISSUE TITLE
Feature request: Infinite horizontal workspace

### ISSUE THREAD

**Issue by ludvigng** [kwin-scripts/kwin-tiling#241]
Hi!

Any chance to get support for the kind of workspace design that the [PaperWM](https://github.com/paperwm/PaperWM) project for gnome-shell uses?

New windows are placed to the right of the focused window, with a workspace that just keeps expanding horizontally with every window. This workspace is scrollable, and the active window is always fully visible (and can be centered with super+c)

An example from the paperwm github, where we can see the horizontal list of windows when switching, along with the terminal window on the right being partially outside the current view: ![image](https://raw.githubusercontent.com/paperwm/media/master/tiling.png)

This image shows the scrolling in action, where the main window is centered (and then put in an added suggestion of a 'zen mode'):
![animation](https://user-images.githubusercontent.com/72201/67148809-09885a00-f2a4-11e9-96d9-51a577ec15bd.gif)

I realize it might be way outside of this projects scope, but I think it's such a good design I have a hard time switching to something else. :)

**Comment by faho** [comment]
This is out of scope, yes. I also don't think it's possible with KWin's current APIs. Sorry!

**Comment by piotr-dobrogost** [comment]
> I also don't think it's possible with KWin's current APIs. Sorry!

Theoretically to implement this one only needs the ability to resize and position windows and both of these are possible with KWin I think.

**Comment by faho** [comment]
That wouldn't help much if it's not scrollable, and we have no way of doing that, not even getting the mouse position.

Even if we did, I wouldn't want to use it and I don't want to implement it myself, and I don't want to merge things that I then have to maintain unless I plan on using them.

So unless someone 1. implemented the necessary features in KWin, 2. wrote it up, 3. committed to maintaining it, it's not going to happen.
