### ISSUE TITLE
Spacing between tiled windows

### ISSUE THREAD

**Issue by James2226** [kwin-scripts/kwin-tiling#243]
Is it possible that there is a way to get spaces between the windows and around the edges of the screen?

**Comment by faho** [comment]
There is, the config menu has a "gaps" tab. Go to systemsettings -> "window management" -> "kwin scripts" and click on the settings icon.

If that doesn't appear you're running into a kpackagetool bug, see https://github.com/kwin-scripts/kwin-tiling#troubleshooting.
