### ISSUE TITLE
Window gap

### ISSUE THREAD

**Issue by Rtful** [kwin-scripts/kwin-tiling#247]
It would be very nice if there was an option to turn on a gap between the windows as I think it helps with differentiating them.

**Comment by faho** [comment]
![Uploading Screenshot_20210814_232200.png…]()

**Comment by faho** [comment]
![Screenshot_20210814_232200](https://user-images.githubusercontent.com/5185367/129460329-849c7311-c222-4b81-bccb-3df0cc51df1e.png)

**Comment by Rtful** [comment]
![image](https://user-images.githubusercontent.com/75473345/129817517-b5a9f5b5-7667-41cd-9b92-eaf138ec917d.png)
I do not have the option to Configure the script

**Comment by faho** [comment]
Ah, yeah.

Unfortunately there's a bug in the KWin extension system that forgets to register these things. You'll have to do [what the README says](https://github.com/kwin-scripts/kwin-tiling#troubleshooting).
