### ISSUE TITLE
Window class exclude rule issue

### ISSUE THREAD

**Issue by eggeek** [kwin-scripts/kwin-tiling#248]
Hi, 
What if a window has multiple window class and one of the class matches to exclude rule, what's the expected behaviour?
For example, I have a drop-down alacritty window (created by tdrop) with `yakuake` class :
```
WM_CLASS(STRING) = "Yakuake", "Alacritty"
```
I expect this window should be ignored because `yakuake` is in black list.
But actually it's not.
I have to also add "alacritty" to make this work, but this means all my terminals are excluded as well, which is not I want.

**Comment by faho** [comment]
The "class" is only the latter value. The former is the "resourceName". Yes, I know, xprop is awful. 

Since #222 we match either. If that doesn't work for you, you're probably using an older version or it's a kwin bug.
