### ISSUE TITLE
Gnome programs resize all tiled windows

### ISSUE THREAD

**Issue by mcleocita** [kwin-scripts/kwin-tiling#251]
Distro: Ubuntu 20.04.3 LTS
DE: KDE Plasma
Kwin version: 5.18.6

https://user-images.githubusercontent.com/25404214/132856586-6e9d5f8a-8821-4ffd-9131-864020f79d65.mp4

**Comment by faho** [comment]
Which browser is that? Does it happen *just* with that, or also without it?

I'm afraid this is looking like it resizes again in response to us resizing it, which isn't in general solvable from our end.

Or it has awkward basicUnits, which aren't a thing anymore in wayland so it needs to move away from them anyway.

**Comment by faho** [comment]
Yeah, this is either #111 or #94. Let's just ignore basicUnits now. If anyone complains about broken clients, we can put them on the ignorelist.
