### ISSUE TITLE
[Feature Request] Enable floating for spesific application

### ISSUE THREAD

**Issue by Uzaaft** [kwin-scripts/kwin-tiling#253]
The title pretty much says it all. Is it possible to implement this feature so that for example my drop down terminal(tdrop with alacritty) avoid being tiled?
Otherwise, great work!

**Comment by faho** [comment]
Please do see the options. It's been implemented for years.

**Comment by Uzaaft** [comment]
The thing is, the floating part will need to be triggered at the run time of the command, and not something that you press a key for. I guess kwin-tiling was not what I imagined, so I`ll have to look elsewhere.

**Comment by faho** [comment]
You can specifically exclude applications, yes. These will always float, without having to press a button.

**Comment by Uzaaft** [comment]
I see. That brings me somewhat towards the goal, but it would not be ideal in my use case. Thank you for your time!
