### ISSUE TITLE
The support for activities failed

### ISSUE THREAD

**Issue by GongSiqiu** [kwin-scripts/kwin-tiling#255]
it seems that the support for activities failed 
![图片](https://user-images.githubusercontent.com/40697840/137908918-cacb77d3-b14c-4e57-b5e3-a3c141e12c5f.png)

Operating System: Kubuntu 21.10
KDE Plasma Version: 5.23.0
KDE Frameworks Version: 5.87.0
Qt Version: 5.15.2
Kernel Version: 5.13.0-19-generic (64-bit)
Graphics Platform: X11
Processors: 12 × AMD Ryzen 5 5600G with Radeon Graphics
Memory: 13.5 GiB of RAM
Graphics Processor: AMD RENOIR

**Comment by faho** [comment]
Sorry I have absolutely no idea what this means.

**Comment by GongSiqiu** [comment]
I have two screens. If I open one window in an activity and another window in another activity in the same workspace,  the result will be like this figure. But it should use the full screen.
