### ISSUE TITLE
upon using 'plasmapkg2 --type kwinscript -i' terminal spits out 'kpackagetool5: Missing value after '-i'.'

### ISSUE THREAD

**Issue by TinHeadIsProducing** [kwin-scripts/kwin-tiling#256]
Trying to install Kwin-scripts using plasmapkg2, what am I supposed to put after '-i'?

**Comment by Katzentante** [comment]
You probably forgot to put an "." at the end.
Like so: `plasmapkg2 --type kwinscript -i .`
