### ISSUE TITLE
Weird behaviour with Thunderbird 91.5

### ISSUE THREAD

**Issue by Warkorentin** [kwin-scripts/kwin-tiling#259]
Hello, 

Kubuntu recently updated Thunderbird from I believe 78.0 to 91.5. 
Since then, Thunderbird has been misbehaving whenever there are more than three windows opened. It results in windows being partially rendered, or in the wrong position. I've added a screenshot. 

![Screenshot_20220204_114810](https://user-images.githubusercontent.com/6535535/152554311-422afc57-dd7c-4c18-b56e-4a0fc143a4ad.png)

Is there anything I can do ? Should I report this to Thunderbird ? 
Thank you !

**Comment by faho** [comment]
This is https://bugs.kde.org/show_bug.cgi?id=341195, which has been closed because apparently nobody wants to work on it. Sorry!
