### ISSUE TITLE
Move window to another screen is not working

### ISSUE THREAD

**Issue by indaleto** [kwin-scripts/kwin-tiling#262]
Hi, I have multiple monitors and multiple tiled windows in one screen but I can't move one of them to next/previous screen with a shortcut. I've defined shift + ctrl + left/right in kwin to move window to previous/left screen but that does not work, unless the window is maximized.

I have the option Window Behaviour -> Separate screen focus checked, but uncheking does not work either.

Is there something I can do? thanks

Using Arch + KDE

**Edit**: After some tweeks (?) I can move windows to the left but not to the right!

**Comment by Dennis-Rall** [comment]
I have the same problem. How did you get moving to the left screen working?

**Comment by faho** [comment]
Duplicate of #88. Multimonitor needs work, and it needs work from someone who uses it.
