### ISSUE TITLE
Application Window visible after start when it should be in tray only

### ISSUE THREAD

**Issue by newhinton** [kwin-scripts/kwin-tiling#264]
Many applications that have the ability to be started in tray do not start in tray when this script is in use. 

Some examples are: KeepassXC, Signal (via cli) or Zettlr (Dev version i think)
This script should not pull windows into visibility when they should not be. How can i fix this behaviour?

**Comment by faho** [comment]
We don't do anything to tray'd windows. If you don't want a client to tile, set it to not tile.
