### ISSUE TITLE
Add 3x2 style grid please.

### ISSUE THREAD

**Issue by ashikur-rahman-shad** [kwin-scripts/kwin-tiling#268]
Can you do something, like adding a 3x2 style grid? That would be great! Unlike the blade layout, it doesn't create any more columns after 3 columns are created. Instead, it makes a new row.  That would be really useful for 4k KDE users like me.

**Comment by faho** [comment]
Use the GridLayout.

I'm happy with the existing layouts as they are and unlikely to add anything else.

A "3x2" grid in particular makes no sense - what if you have fewer or more than 6 windows?
