### ISSUE TITLE
A plasmoid to toggle on/off kwin-scripts

### ISSUE THREAD

**Issue by ashikur-rahman-shad** [kwin-scripts/kwin-tiling#269]
A plasmoid to toggle on/off kwin-scripts would be really great. Please provide any terminal command, that will let us toggle it. I can create a plasmoid myself, that can run that command. This one is a slightly less important issue because one can still do it with the keyboard, but it will sure help to make "kwin-tiling" the best tiling script/manager!

**Comment by RipKord42** [comment]
You can set a hotkey to disable / enable on a workspace by workspace 
basis.  Perhaps this can be extended to global?

**Comment by ashikur-rahman-shad** [comment]
I found a bash script that can do it. I'm a noob. So pardon me for creating an issue without doing enough research.
