### ISSUE TITLE
Rejecting window lineup after desktop change

### ISSUE THREAD

**Issue by greeny277** [kwin-scripts/kwin-tiling#27]
After switching from one desktop to another one (f.e. Ctrl-F1) the further lineup of the 
windows change sometimes. F.e. when one window was maximized before another. After switching, both windows have the same size again and were placed next to each other.

**Comment by faho** [comment]
Okay, since that was written we've changed how maximized windows are handled multiple times, and it's, in my opinion, sensible now.
