### ISSUE TITLE
Exclude based on window class AND name

### ISSUE THREAD

**Issue by magnific0** [kwin-scripts/kwin-tiling#62]
I want to be able to exclude windows from tiling if the class and name is matched. I used to be able to do this with Awesome WM. 

My specific use case is Matlab, where the main window should be tiled, but any figures free floating.

**Comment by faho** [comment]
Any idea what the UI for this should look like? We're a bit constrained here by just being able to add a Qt .ui file (AFAIK).

**Comment by magnific0** [comment]
Something like this should work fine: 
![tiling_exclusion_settings](https://cloud.githubusercontent.com/assets/2254149/16769696/0928c890-484a-11e6-9da4-0b51687d2b83.png)

Note that the Window Rules setting in KWin allows for rules based on Class, title, role, type and hostname.
![window_rules](https://cloud.githubusercontent.com/assets/2254149/16769760/4cae1f66-484a-11e6-9e56-80e492c25205.png)

Do you know whether the current exclusion class name matches fuzzy or allows for wildcards?

**Comment by faho** [comment]
>Something like this should work fine: 

Yeah, that looks kinda nice.

>One could leave either one blank or fill in both. A secondary, much more hacky approach would be to separate match rules in a single string (class|title).

That would possibly be what we need to do anyway. I'm not sure the configuration can store something this complicated (there's a workaround in the code where Qt doesn't correctly store an arraylist, so we just store it as a string joined with ",", so I don't trust this part of Qt. I might need to recheck).

>Note that the Window Rules setting in KWin allows for rules based on class, title, role, type and hostname.

Yes, and I'd love to be able to use that (by allowing a custom "attribute" to be added there or similar). I haven't gotten around to filing a feature request upstream.

>Do you know whether the current exclusion class name matches fuzzy or allows for wildcards?

It's [an exact match](https://github.com/faho/kwin-tiling/blob/master/contents/code/tilelist.js#L379) only.

**Comment by v3ss0n** [comment]
Can we get kwin script read a config file? and we list those excludes there for now ? (until kde bother to fix bugs that is years old)

**Comment by faho** [comment]
>Can we get kwin script read a config file?

It already does - ~/.config/kwinrc. That's the backing store for the "readConfig" function. We can store any arbitrary strings in there. The issue is getting a UI to properly enter something. And the options there are rather limited (and got more limited a while back).

**Comment by schemar** [comment]
I would also need this (for slack mini panels). I would also be ok with a second, separate input "Excluded window titles". Any window where the class matches an excluded class *or* a title matches an excluded title, is excluded from tiling.

**Comment by faho** [comment]
Since #222, we also match the resourceName so this should be handled.
