### ISSUE TITLE
Can't specify excluded window classes

### ISSUE THREAD

**Issue by ShibaOnTheMoon** [kwin-scripts/kwin-tiling#64]
I've installed kwin-tiling recently, but it seems that the config UI is broken : I can't specify the classes to exclude, there is nothing under "Excluded window classes".

**Comment by faho** [comment]
Yep, seems KEditListWidget has been removed.... Now to find a replacement...

**Comment by v3ss0n** [comment]
Yea same problem for me in #61  , i ended up  editing the javascript and setting excludes statically.

**Comment by jayx101** [comment]
@v3ss0n , having the same problems and would like to also statically exclude krunner, yakuake etc. would you mind tilling me where / how you edited the js?

**Comment by faho** [comment]
@jayx101: In ~/.local/share/kwin/scripts/kwin-script-tiling/contents/code/tilelist.js, line 376 is

```js
	var fl = "yakuake,krunner,plasma,plasma-desktop,plugin-container,Wine,klipper,plasmashell,Plasma,ksmserver, pinentry";
```

Add the window classes (the second thing in the "WM_CLASS(STRING) =" line of the output of running `xprop` and clicking on the window) you'd like to exclude there.

However, both krunner and yakuake should already be included by default. Are you experiencing any problems with those?

**Comment by jayx101** [comment]
thanks @faho ill take a look!

currently it is not including the defaults.

so just some background info to the problem:
Initially the floats were working. i.e. krunner and yakuake. However settings in KWin scripts were not.. I wanted to configure the gaps, but wasnt able to. I tried to change the vals in the main.xml file but that didnt have any effect.

I was able  to fix the settings by changing the path in the kwin-script-kwin-script-tiling.desktop.

After I implemented  the fix, the settings worked and I was able to change the gaps.. however the floating settings were now being ignored. I added them to the settings dialog but it makes no difference.

I have also completely removed and re-installed but also makes no difference. I am assuming it is related to the KEditListWidget issue you mentioned above?

**Comment by jayx101** [comment]
Seems its related to the the settings being retrieved from the readConfig. 

I ended up just bypassing the readConfig as below and is now working

`376     var fl = "yakuake,krunner,plasma,plasma-desktop,plugin-container,Wine,klipper,plasmashell,Plasma,ksmserver, pinentry";
377     // TODO: This could break if an entry contains whitespace or a comma - it needs to be validated on the qt side
378     //var floaters = String(KWin.readConfig("floaters", fl)).replace(/ /g,"").split(",");
379     var floaters = String(fl).replace(/ /g,"").split(",");
`

**Comment by faho** [comment]
@jayx101: Ah yes, you have configured the script before, and most likely you had removed yakuake and krunner. That means you have the configuration still stored in ~/.config/kwinrc - there's a "[Script-kwin-script-tiling]" section with a "floaters=" line. You could also have modified that one. Sorry, I forgot about that.

**Comment by v3ss0n** [comment]
?any solution for this without doing statically

**Comment by faho** [comment]
Not yet. I've tried some things, like just making the widget a QLineEdit instead (so you'd have to enter comma-separated classes), but I can't get it to use the default value. Which would suck because then the first thing you add would remove all the defaults.

I could of course hard-code the default exceptions - there's no reason to tile them anyway...

**Comment by jayx101** [comment]
Had a look, and the floaters there is blank as you mentioned

![image](https://cloud.githubusercontent.com/assets/12130063/17642334/86d651ee-6173-11e6-93b2-b11735684ebc.png)

Thanks so much for all the help. Loving the tiling now!

**Comment by demonFudgePies** [comment]
Just to let you know I had the same problem with krunner not being excluded, and the solution @jayx101 provided worked for me (bypassing the config file). My kwinrc file also has blank next to floaters, and I never configured anything regarding the script before.

**Comment by faho** [comment]
So, it seems like under certain circumstances kwin will write an empty config. I've also gotten that but haven't been able to recreate the circumstances.

I'm leaning towards just hard-coding the default excludes, since they aren't something you want to tile. Stuff like krunner, yakuake and plasma-desktop in particular. That just looks ugly, wrong and wastes space.

However, we also have "wine" in the default list. Does anyone here want to have wine windows tiled? Does that work for some?

**Comment by v3ss0n** [comment]
also everything that eclipse trows .. XMind , Eclipse , etc.

**Comment by v3ss0n** [comment]
also InkSkape dosen't work well in tiling mode either.

**Comment by faho** [comment]
>also everything that eclipse trows .. XMind , Eclipse , etc.

I've actually added some hardcodes for those (since they cannot be identified just by WM_CLASS). Do you have 87de962?

>also InkSkape dosen't work well in tiling mode either.

Never tested that. Might have to try.

**Comment by faho** [comment]
>also InkSkape dosen't work well in tiling mode either.

So, I've just tested it, and I can only see one issue: It'll start at full screen size, reducing other tile sizes to 0. Otherwise, it actually seems to be working nicely.

This is with 2bfcac0. @v3ss0n: Can you try that commit?

**Comment by v3ss0n** [comment]
```
qml: Testing configuration                                                                                                                                                                                                                     
qml: Reading floaters                                                                                                                                                                                                                          
qml: We're running under KWin 5                                                                                                                                                                                                                
qml: Starting tiling                                                                                                                                                                                                                           
qml: Creating HalfLayout                                                                                                                                                                                                                       
qml: Creating HalfLayout                                                                                                                                                                                                                       
qml: Creating HalfLayout                                                                                                                                                                                                                       
qml: Creating HalfLayout                                                                                                                                                                                                                       
qml: Creating HalfLayout                                                                                                                                                                                                                       
qml: Creating HalfLayout                                                                                                                                                                                                                       
qml: Creating HalfLayout                                                                                                                                                                                                                       
qml: Creating HalfLayout                                                                                                                                                                                                                       
qml: Creating HalfLayout                                                                                                                                                                                                                       
qml: floaters = []                                                                                                                                                                                                                                        
           
```
Floaters ended up empty , i think the config is returning null. Now every floaters got tiled :o

**Comment by v3ss0n** [comment]
```
	var fl = "XMind,Eclipse,java,YaKuake,yakuake,krunner,plasma,plasma-desktop,plugin-container,Wine,klipper,plasmashell,Plasma,ksmserver, pinentry";
	// TODO: This could break if an entry contains whitespace or a comma - it needs to be validated on the qt side
	var floaters = String(fl).replace(/ /g,"").split(",");
  console.log("floaters=",floaters)
```
i had forced like this to work.

**Comment by faho** [comment]
@v3ss0n: Please read on, the eclipse thing is a different piece of code, because it cannot be identified via WM_CLASS. eclipse itself tiles well (IIRC), but some of its dialogs and such don't, and it does not set a identifiable WM_CLASS for them (which is what that list contains).

So, there's https://github.com/faho/kwin-tiling/blob/master/contents/code/tilelist.js#L371-L377:

```javascript
	// HACK: Eclipse's quick outline (and possibly other windows) closes when it loses focus
	// with FFM and this script, that happens a ton
	// Unfortunately, this is still declared as a normal window
	if (client.resourceClass.toString() == "eclipse"
		&& client.transient == true) {
			return true;
}
```

which was added in 87de96292ede569fadb83f1c537b28705be28a64, to fix #57.

Again: Do you have that commit? If so, eclipse special windows should not be tiled. eclipse itself, the main window, should work IIRC.

>Floaters ended up empty , i think the config is returning null. Now every floaters got tiled :o 

That I just mentioned. Sometimes kwin writes an empty config setting, and we currently only provide defaults. We should probably provide a hardcoded list of stuff that won't be tiled _in addition_ to your config.

**Comment by v3ss0n** [comment]
Thanks @faho  , how to make the config not empty ?

**Comment by faho** [comment]
@v3ss0n: Remove the "floaters=" line from ~/.config/kwinrc.

But I'd also like to talk about your eclipse and inkscape comments: 

- Does eclipse not work for you? Is it the main window or a dialog?

- What is wrong with inkscape?

**Comment by v3ss0n** [comment]
About dialog got tiled too ( Xmind, which is build using Eclipse RCP)
![xmind](https://cloud.githubusercontent.com/assets/419606/20033988/784bdcd2-a3dd-11e6-915a-383f2337348c.png)


In inkskape , when you click file > document properties , it apparently freeze , until you move the window to reset tiling.

**Comment by faho** [comment]
@v3ss0n: d94684d should fix your issues with inkscape, e409fb7 the issue with floaters being empty.

**Comment by v3ss0n** [comment]
@faho  floaters being empty working fine but transient windows aren't working , yet. Do i need to set the parent windows to be regarded as floaters first?  Both XMind and InkSkape behave same.

**Comment by faho** [comment]
>Do i need to set the parent windows to be regarded as floaters first? Both XMind and InkSkape behave same.

No. The parent window should tile normally, and the "dialog" should float.

That seems to work for me, both with xmind's "about" and inkscapes "document properties".

**Comment by faho** [comment]
What I mean by that is, you shouldn't have to do anything. The "dialog" should float automatically. The parent window should usually be able to float (and that is okay for me with xmind and inkscape, except inkscape starts maximized).

**Comment by v3ss0n** [comment]
thanks its working now , kwin got duplicated entry with old and new version.
Not sure which one is which and what to delete lol:
![bugged](https://cloud.githubusercontent.com/assets/419606/20035414/d6c69444-a411-11e6-9ea5-19a68d654aed.png)

**Comment by laloch** [comment]
Maybe we could reuse Breeze decoration exception UI...
https://cgit.kde.org/breeze.git/tree/kdecoration/config/ui/breezeexceptionlistwidget.ui

**Comment by faho** [comment]
Okay, the original issue here was the edit ui being broken, that's long been fixed.
