### ISSUE TITLE
Make direction of blade layout configurable

### ISSUE THREAD

**Issue by piotr-dobrogost** [kwin-scripts/kwin-tiling#76]
Currently the blade layout positions windows one next to the other (windows are maximized vertically). There should be an option to position windows one below the other (windows maximized horizontally). This would make the layout much more useful for screens rotated 90°.

**Comment by faho** [comment]
The easiest way to do this is another layout, because there's no per-layout configuration options (well, there is the concept of a "master" that a layout can support).

**Comment by piotr-dobrogost** [comment]
Having this as separate layout seems OK for now; I guess HorizontalBlade and VerticalBlade could be the names. I wonder if something like direction (horizontal, vertical) wouldn't in a long run be a desirable option for most/all layouts? For instance Half Layout could make use of this as well. How would you envision per-layout configuration options? Would having some keyboard shortcut per option with (preferably) visual feedback of the value chosen work?
