### ISSUE TITLE
Grid layout

### ISSUE THREAD

**Issue by cognifloyd** [kwin-scripts/kwin-tiling#78]
I'm using Plasma 5 on gentoo.

Please add a layout so that I can have more of a grid layout for various windows (in configurations of 2-5 columns and 2-7 rows).

I would imagine something like the following terminator layout where I can drag the edges of windows arranged in a grid to modify how wide or tall a particular square is:
![](https://i.stack.imgur.com/MzR9i.png)

Background:
I want to tile Konsole sessions, but, Konsole doesn't support this terminator-like grid. Thus, I tried using kwin-tiling to achieve the same effect. Konsole has split-view, but that's very different), and I don't really want my Konsole sessions open in the same window because I use window rules to change the color of the window decorations based on the title of the window (the title reflecting which machine I'm connected to over ssh).

**Comment by faho** [comment]
As you might have noticed, I haven't been working much on this project, so I'm not going to be implementing this.

I'd appreciate a PR that does it, and will be available to provide guidance.
