### ISSUE TITLE
Questions (probably not actually issues!)

### ISSUE THREAD

**Issue by TRPB** [kwin-scripts/kwin-tiling#85]
This is likely a documentation issue rather than a problem with the code. Firstly, I love this. I was looking for  something similar to i3 but I like the eye candy of kwin so discovering this is wonderful. It works beautifully however i have a few questions:

1.  How do I control where new windows will appear? On i3 there is a visual indicator showing where the next window will come up

2. I can drag and drop windows to move their positions, is there a way of using keys to do this? E.g. meta+arrow keys to move the focused window?

3. I don't think this exists and it's not a huge issue but is there anything similar to i3's vertical/horizontal split?

Depending on how i get on I might fork this and add some extra functionality. I know javascript well but not kwin scripts.

**Comment by faho** [comment]
>How do I control where new windows will appear? On i3 there is a visual indicator showing where the next window will come up

KWin has some placement options in systemsettings -> window management -> window behavior -> advanced (all terms translated manually). One of them is "under cursor". The script in turn has three possible choices:

- Respect KWin's decision (default)

- Always open new windows as the "master" window (i.e. at the beginning of the list)

- Always open new windows in a new tile at the end

>I can drag and drop windows to move their positions, is there a way of using keys to do this? E.g. meta+arrow keys to move the focused window?

Yes, there are. See the shortcut settings for KWin - the "Move Window *" entries, defaulting to Meta+Shift+{H,J,K,L} (vi-style).

>I don't think this exists and it's not a huge issue but is there anything similar to i3's vertical/horizontal split?

I've never used i3 much. I'm assuming this is the "split this container vertically" thing where you can define your tiling layout on-the-fly? If so, that's #19. I won't implement it myself, but if anyone else wants to, I'm eagerly awaiting pull requests!

>I know javascript well but not kwin scripts.

I don't really know javascript all that well but I've probably written the most kwin scripts out of anyone 😄.  Anyway, there's not _that_ much to learn - the basic documentation is at https://techbase.kde.org/Development/Tutorials/KWin/Scripting/API_4.9, the rest is figuring out which parts work.

**Comment by TomBZombie** [comment]
thanks for the quick reply. As others, I've come from i3 (Well actually I've used kde for years, tried i3 and loved the concept but it feels dated). I'm going to fork and try to implement  a few changes

1. Split v/h which controls where the window will appear (relative to current focused window) and display a visual cue (possibly by creating a new window briefly) briefly. It probably requires a new layout, or redefining the layout on the fly but I'm sure it's possible.

2. Some soft of visual indicator that shows whenever you split (or possibly on a key press) that shows where the next window will open. Could even be as simple as starting a crude program that just creates a placeholder window in the next position then closing it.

3. Trigger the "window open" effect every time a window is resized. E.g. wobbly windows, slide, grow or some other existing animation effect. At the moment it's instant, which is fine, but a bit of animation would fit better with KDE :)

**Comment by TomBZombie** [comment]
One more quick question, is it possible to update the config without logging in and out? E.g. changing border sizes or any of the checkboxes works, but the new settings aren't applied unless I log out and back in.

**Comment by faho** [comment]
Unfortunately not-

This would require either reading the config right when it is needed or hooking up to the "configChanged" signal, but last I tried (years ago) this didn't work properly - the return value of "readConfig" never changed.

**Comment by suhailshergill** [comment]
@faho @TRPB logging out and back in isn't necessary. `kwin --replace` is sufficient to for the new settings to be applied.
