### ISSUE TITLE
gvim not working

### ISSUE THREAD

**Issue by flosse** [kwin-scripts/kwin-tiling#9]
The gvim window and its content is totally transparent.
- kwin-tilling 1.3.1.2
- kde 4.11.3
- gvim 7.4.86

**Comment by anntzer** [comment]
Same issue here.  Sometimes I see a transparent gvim that works fine after redrawing, sometimes a black window that does not respond, and sometimes a normal looking window with the vim GUI menu (which I disabled in my vimrc) that does not respond either.

**Comment by faho** [comment]
See #6 - this is a duplicate.
