### ISSUE TITLE
Gap sizes incorrect when 3 or more windows open

### ISSUE THREAD

**Issue by Powerlated** [kwin-scripts/kwin-tiling#94]
![image](https://user-images.githubusercontent.com/7016749/35251906-ac8088c4-ffab-11e7-82b4-4c82eb97c6c8.png)

I am on commit 364255929f5f7742cef23cfc7203df10495d6848, and attached a file showing the bug.

**Comment by faho** [comment]
Yeah.... this is probably caused by the minSize on one of those windows being hit, so it's getting resized, and some calculation somewhere is off.

Unfortunately, it seems that kwin now no longer shows the output of `print()`, so I currently have no real way of debugging this.

**Comment by rittelle** [comment]
Hi, 
I just recently stumbled upon your project (and I am using it right now), so thanks for creating this!

You actually can monitor your prints by monitoring the DBus as every print gets sent via a signal.
Inspired by this script I started toying around with KWin myself and this works for me:
```
dbus-monitor "type=signal,sender='org.kde.KWin',path='/$ID',interface='org.kde.kwin.Scripting'"
```
The output could use some preprocessing, but it works for me.

**Comment by laloch** [comment]
Hi @Powerlated, is this still an issue with the latest release or master/HEAD?

**Comment by gabrieldnzs** [comment]
Hi, thanks for effort on the project, it really helps me on my productivity.

I think my problem is related with this issue. Both rxvt-unicode and st have problems creating new windows. With Konsole and other programs there is no problem when creating new windows. Here are some prints:

This is ST, same happen to rxvt-unicode:

![tiling_st_issue](https://user-images.githubusercontent.com/38968716/58180702-e91a8c00-7c80-11e9-80a7-52df2e2b1726.png)

This is with konsole, works as expected:

![tiling_konsole](https://user-images.githubusercontent.com/38968716/58180872-2a12a080-7c81-11e9-883a-428bf3d033ad.png)

I can send more info if you need. Thanks.

**Comment by laloch** [comment]
I can confirm the issue with `urxvt`. It seems to be a problem common to all tiling window managers - [see here](https://faq.i3wm.org/question/6989/resize-issue-with-urxvt.1.html)

**Comment by faho** [comment]
`st` has:

WM_NORMAL_HINTS(WM_SIZE_HINTS):
                program specified size: 884 by 532
                program specified resize increment: 11 by 22
                program specified base size: 4 by 4

`rxvt-unicode` has

WM_NORMAL_HINTS(WM_SIZE_HINTS):
                program specified minimum size: 22 by 17
                program specified resize increment: 6 by 13
                program specified base size: 16 by 4
                window gravity: NorthWest

`konsole` has

WM_NORMAL_HINTS(WM_SIZE_HINTS):
                user specified size: 1866 by 1034
                program specified minimum size: 42 by 57
                program specified resize increment: 2 by 2
                program specified base size: 0 by 0
                window gravity: Static

Yeah, it's the resize increments (aka "basicUnit".

Personally, I'd love to just remove that thing entirely (it's gone in wayland), but if we did that urxvt would just keep trying to resize.

**Comment by gabrieldnzs** [comment]
Well, at least i found a solution to st, as it is source based. I applied this [patch](https://st.suckless.org/patches/anysize/) to the source code and it worked. I didn't searched for workarounds to other terminal emulators, but maybe there are some solutions for who wants to use other terminals.

Here is st now with the script:

![tiling_st](https://user-images.githubusercontent.com/38968716/58194969-4c1a1c00-7c9d-11e9-81c0-de5c66111b51.png)

**Comment by ilyam8** [comment]
Gaps changes does not apply on the fly, plasma session have to be restarted. At least that did the trick for me. Is this a bug?

**Comment by faho** [comment]
KWin doesn't propagate config changes - we can call readConfig until we're blue in the face and still get the same answer. So it's not a bug in the script, and I'm pretty sure it's known upstream.

**Comment by ilyam8** [comment]
Ok, thanks. I tried `gaps` feature, but it is kind of broken.

What i did:
 - enabled gaps
 - opened ~15 applications (i3 layout) - tiles were not equal in size.
 - started to swtich quickly layouts - PC started to lag, i could watch tile changing size process, it was very slow, sometimes plasma session even froze (1 cpu core 100% constantly)

I see no such problems^^ w/o gaps.

Is this known or should i open an issue?
